### ISSUE TITLE
batchskl: panic due to index out of range

### ISSUE THREAD

**Issue by nicktrav** [cockroachdb/pebble#1258]
Reported in cockroachdb/cockroach#69906.

We're hitting the following in `batchskl.Skiplist`:

```console
panic.go:679: runtime error: index out of range [4294967264] with length 0
--
runtime.boundsError
panic.go:679: *withstack.withStack (top exception)

/usr/local/go/src/runtime/panic.go in runtime.gopanic at line 679
/usr/local/go/src/runtime/panic.go in runtime.goPanicIndex at line 75
vendor/github.com/cockroachdb/pebble/internal/batchskl/skl.go in github.com/cockroachdb/pebble/internal/batchskl.(*Skiplist).node at line 296
vendor/github.com/cockroachdb/pebble/internal/batchskl/skl.go in github.com/cockroachdb/pebble/internal/batchskl.(*Skiplist).newNode at line 265
vendor/github.com/cockroachdb/pebble/internal/batchskl/skl.go in github.com/cockroachdb/pebble/internal/batchskl.(*Skiplist).Add at line 233
vendor/github.com/cockroachdb/pebble/batch.go in github.com/cockroachdb/pebble.(*Batch).Delete at line 528
pkg/storage/pebble_batch.go in pkg/storage.(*pebbleBatch).Clear at line 240
pkg/kv/kvserver/replica_raft.go in pkg/kv/kvserver.handleTruncatedStateBelowRaft at line 1696
pkg/kv/kvserver/replica_application_state_machine.go in pkg/kv/kvserver.(*replicaAppBatch).runPreApplyTriggersAfterStagingWriteBatch at line 702
pkg/kv/kvserver/replica_application_state_machine.go in pkg/kv/kvserver.(*replicaAppBatch).Stage at line 484
pkg/kv/kvserver/apply/cmd.go in pkg/kv/kvserver/apply.mapCmdIter at line 175
pkg/kv/kvserver/apply/task.go in pkg/kv/kvserver/apply.(*Task).applyOneBatch at line 280
pkg/kv/kvserver/apply/task.go in pkg/kv/kvserver/apply.(*Task).ApplyCommittedEntries at line 247
pkg/kv/kvserver/replica_raft.go in pkg/kv/kvserver.(*Replica).handleRaftReadyRaftMuLocked at line 765
pkg/kv/kvserver/replica_raft.go in pkg/kv/kvserver.(*Replica).handleRaftReady at line 425
pkg/kv/kvserver/store_raft.go in pkg/kv/kvserver.(*Store).processReady at line 484
pkg/kv/kvserver/scheduler.go in pkg/kv/kvserver.(*raftScheduler).worker at line 226
pkg/kv/kvserver/scheduler.go in pkg/kv/kvserver.(*raftScheduler).Start.func2 at line 166
pkg/util/stop/stopper.go in pkg/util/stop.(*Stopper).RunWorker.func1 at line 222
/usr/local/go/src/runtime/asm_amd64.s in runtime.goexit at line 1357
```

This corresponds to Pebble SHA [`c3ef93f9a9edfa7a8ad8d897df6719a7deeba71d`](https://github.com/cockroachdb/pebble/blob/c3ef93f9a9edfa7a8ad8d897df6719a7deeba71d).

The relevant code is around here: https://github.com/cockroachdb/pebble/blob/c3ef93f9a9edfa7a8ad8d897df6719a7deeba71d/internal/batchskl/skl.go#L274-L297

Based on the stacktrace, I think what might be happening is the following:

- large skiplist with `len(nodes)=4294967264` (value of `offset`)
- we compute `newSize` as `4294967264 + size`
- we then resize `s.nodes` to `s.nodes[:newSize]`
- the stacktrace tells us the length of nodes was 0
- working backwards, size was most likely 32, given that `(4294967264 + 32) mod 2^32 == 0`

**Comment by jbowens** [comment]
Is it possible there was an _underflow_? Not sure how

**Comment by bananabrick** [comment]
Slightly unrelated, but on a 32 bit system, this cast will also cause issues: https://github.com/cockroachdb/pebble/blob/c3ef93f9a9edfa7a8ad8d897df6719a7deeba71d/internal/batchskl/skl.go#L263, won't it?

**Comment by nicktrav** [comment]
Reproducer:

```go
func Test(t *testing.T) {
	opts := &Options{
		FS: vfs.NewMem(),
	}
	db, err := Open("", opts)
	if err != nil {
		panic(err)
	}
	defer db.Close()

	b := db.NewIndexedBatch()
	for i := 0; i < (1 << 32); i++ {
		s := strconv.Itoa(i)
		if err = b.Set([]byte(s), []byte{}, nil); err != nil {
			panic(err)
		}
		if (i % (1 << 25)) == 0 {
			fmt.Printf("added %d items to batch\n", i)
		}
	}

	if err = b.Commit(nil); err != nil {
		panic(err)
	}
	defer b.Close()
}
```

```console
--- FAIL: Test (34.52s)
panic: runtime error: index out of range [4294967272] with length 8 [recovered]
	panic: runtime error: index out of range [4294967272] with length 8

goroutine 19 [running]:
testing.tRunner.func1.2(0x46ad0e0, 0xc0001d0228)
	/nix/store/l7w2b12gyhznbv6df50n4j9y3x8ga659-go-1.16.7/share/go/src/testing/testing.go:1143 +0x332
testing.tRunner.func1(0xc000186a80)
	/nix/store/l7w2b12gyhznbv6df50n4j9y3x8ga659-go-1.16.7/share/go/src/testing/testing.go:1146 +0x4b6
panic(0x46ad0e0, 0xc0001d0228)
	/nix/store/l7w2b12gyhznbv6df50n4j9y3x8ga659-go-1.16.7/share/go/src/runtime/panic.go:965 +0x1b9
github.com/cockroachdb/pebble/internal/batchskl.(*Skiplist).node(...)
	/Users/nickt/Development/pebble/internal/batchskl/skl.go:296
github.com/cockroachdb/pebble/internal/batchskl.(*Skiplist).newNode(0xc0001d47f0, 0x4d2ec68200000001, 0x4d2ec68d4d2ec684, 0x3131373136383531, 0x3131373136383531)
	/Users/nickt/Development/pebble/internal/batchskl/skl.go:265 +0x170
github.com/cockroachdb/pebble/internal/batchskl.(*Skiplist).Add(0xc0001d47f0, 0xc04d2ec682, 0x0, 0xc00028bf01)
	/Users/nickt/Development/pebble/internal/batchskl/skl.go:233 +0x29b
github.com/cockroachdb/pebble.(*Batch).Set(0xc0001d46e0, 0xc00028bf00, 0x9, 0x20, 0xc00028bef7, 0x0, 0x0, 0x0, 0x0, 0x0)
	/Users/nickt/Development/pebble/batch.go:514 +0xde
github.com/cockroachdb/pebble.Test(0xc000186a80)
	/Users/nickt/Development/pebble/test_test.go:26 +0x23b
testing.tRunner(0xc000186a80, 0x470c380)
	/nix/store/l7w2b12gyhznbv6df50n4j9y3x8ga659-go-1.16.7/share/go/src/testing/testing.go:1193 +0xef
created by testing.(*T).Run
	/nix/store/l7w2b12gyhznbv6df50n4j9y3x8ga659-go-1.16.7/share/go/src/testing/testing.go:1238 +0x2b3
```

**Comment by nicktrav** [comment]
In terms of the fix (to paraphrase an internal conversation), we probably want to bubble up an error from `(*skiplist).Add()` and remove the panics from `pebble/batch.go`.

**Comment by nicktrav** [comment]
Linking this to cockroachdb/cockroach#75793 too, as that patch effectively guards against growing the skiplist to a size at which this bug becomes more likely.
