### ISSUE TITLE
panic: facing index out of bounds error in Batch ops

### ISSUE THREAD

**Issue by ajatprabha** [cockroachdb/pebble#1599]
Hi, I'm trying to run a simple benchmark but I'm getting index out of bounds error. I see a few other issues like this when using Batch or IndexedBatch. Is this a known issue?

### Steps to reproduce
pebble_test.go
```go
func BenchmarkPebble(b *testing.B) {
	b.ResetTimer()

	for i := 0; i < b.N; i++ {
		b.StopTimer()

		path, err := ioutil.TempDir("", "")
		if err != nil {
			b.Errorf("creating temp dir: %s", err)
		}
		b.Logf("temp directory: %s", path)

		b.StartTimer()

		if err := runPebble(path, &pebble.Options{}); err != nil {
			b.Errorf("running scenario: %s", err)
		}

		b.StopTimer()

		if err := os.RemoveAll(path); err != nil {
			b.Errorf("can't delete: %s", err)
		}
	}
}
```

pebble.go
```go
func runPebble(path string, opts *pebble.Options) error {
	ds, err := pebble.Open(path, opts)
	if err != nil {
		return fmt.Errorf("creating datastore: %s", err)
	}
	defer func() {
		if err := ds.Flush(); err != nil {
			panic(err)
		}
		if err := ds.Close(); err != nil {
			panic("Closing datastore: " + err.Error())
		}
	}()

	if err := runPebbleWorkload(ds); err != nil {
		return fmt.Errorf("running workload: %s", err)
	}

	return err
}

func runPebbleWorkload(ds *pebble.DB) error {
	keySize := 16
	valueSize := 1024 * 1024
	numItems := 10000

	keys := make([][]byte, numItems)

	wg := &sync.WaitGroup{}
	waitCh := make(chan struct{})
	errCh := make(chan error, 1)
	b := ds.NewIndexedBatch()
	for i := 0; i < numItems; i++ {
		wg.Add(1)

		go func(i int, wg *sync.WaitGroup) {
			defer wg.Done()

			r := rand.New(rand.NewSource(22))

			keys[i] = make([]byte, keySize)
			value := make([]byte, valueSize)

			if _, err := r.Read(keys[i]); err != nil {
				errCh <- fmt.Errorf("generating key: %s", err)
			}
			if _, err := r.Read(value); err != nil {
				errCh <- fmt.Errorf("generating value: %s", err)
			}

			if err := b.Set(keys[i], value, &pebble.WriteOptions{}); err != nil {
				errCh <- fmt.Errorf("making update: %s", err)
			}
		}(i, wg)
	}

	go func(wg *sync.WaitGroup) {
		wg.Wait()
		errCh <- b.Commit(&pebble.WriteOptions{})
		waitCh <- struct{}{}
	}(wg)

	select {
	case <-waitCh:
	case err := <-errCh:
		return err
	}

	wg = &sync.WaitGroup{}
	waitCh = make(chan struct{})

	b = ds.NewIndexedBatch()
	for i := 0; i < numItems; i++ {
		wg.Add(1)

		go func(i int, wg *sync.WaitGroup) {
			defer wg.Done()

			if err := b.Delete(keys[i], &pebble.WriteOptions{}); err != nil {
				errCh <- fmt.Errorf("deleting: %s", err)
			}
		}(i, wg)
	}

	go func(wg *sync.WaitGroup) {
		wg.Wait()
		errCh <- b.Commit(&pebble.WriteOptions{})
		waitCh <- struct{}{}
	}(wg)

	select {
	case <-waitCh:
	case err := <-errCh:
		return err
	}

	return nil
}
```

### Error

```bash
goos: darwin
goarch: amd64
pkg: benchdb
cpu: Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
BenchmarkPebble
    benchmark_test.go:73: temp directory: /var/folders/vy/8r91d4lx2bg2p19152s3tt1r0000gn/T/997450210
panic: runtime error: slice bounds out of range [1048610:1048609]

goroutine 32 [running]:
github.com/cockroachdb/pebble/internal/batchskl.(*Skiplist).Add(0xc0000d4110, 0xc000100021, 0x100000, 0x1)
	/Users/admin/.go/pkg/mod/github.com/cockroachdb/pebble@v0.0.0-20220323190648-7ad3551b2050/internal/batchskl/skl.go:206 +0x6fe
github.com/cockroachdb/pebble.(*Batch).Set(0xc0000d4000, 0xc0002b6000, 0x10, 0x10, 0xc0004c4000, 0x100000, 0x100000, 0xc00015e70f, 0x0, 0x0)
	/Users/admin/.go/pkg/mod/github.com/cockroachdb/pebble@v0.0.0-20220323190648-7ad3551b2050/batch.go:511 +0xde
benchdb.runPebbleWorkload.func1(0x10, 0xc000380000, 0x2710, 0x2710, 0x100000, 0xc000122240, 0xc00011c060, 0x2, 0xc000128160)
	/Users/admin/Workspace/benchdb/pebble.go:60 +0x40b
created by benchdb.runPebbleWorkload
	/Users/admin/Workspace/benchdb/pebble.go:45 +0x1eb
```

**Comment by bananabrick** [comment]
Hi, thanks for the question and the reproducible example.

You might have to create a single batch for each goroutine. As of now, the program has a data race, which you'll detect if you run the program with the `-race` flag.

We also have some benchmark numbers here: https://cockroachdb.github.io/pebble/

**Comment by ajatprabha** [comment]
Thanks @bananabrick for pointing me to the benchmark code. This helped! :)
