### ISSUE TITLE
Unhelpful error message for file.Sync: "invalid argument"

### ISSUE THREAD

**Issue by gonzojive** [cockroachdb/pebble#1689]
I am encountering this error message trying to run cockroachdb on a `hostPath` PersistentVolume on a minikube cluster.

The error message "invalid argument" makes it hard to diagnose what is going wrong.

```
panic: fatal: MANIFEST dirsync failed: sync /cockroach/cockroach-data: invalid argument [recovered]
        panic: fatal: MANIFEST dirsync failed: sync /cockroach/cockroach-data: invalid argument

goroutine 38 [running]:
github.com/cockroachdb/pebble.Open.func1(0xc00120bbd0, 0xc00022f000, 0xc0003d4000)
        /go/src/github.com/cockroachdb/cockroach/vendor/github.com/cockroachdb/pebble/open.go:93 +0x187
panic(0x4ee0520, 0xc000e6f338)
        /usr/local/go/src/runtime/panic.go:971 +0x499
github.com/cockroachdb/pebble.setCurrentFunc.func1(0x9, 0x0, 0x0)
        /go/src/github.com/cockroachdb/cockroach/vendor/github.com/cockroachdb/pebble/version_set.go:715 +0xfc
github.com/cockroachdb/pebble.(*versionSet).logAndApply.func1(0xc0011cf500, 0xc00120bb58, 0xc00088ba40, 0xc00120b6a8, 0xc00120b690, 0x9, 0x6, 0xa, 0x1, 0x0, ...)
        /go/src/github.com/cockroachdb/cockroach/vendor/github.com/cockroachdb/pebble/version_set.go:458 +0x4bc
github.com/cockroachdb/pebble.(*versionSet).logAndApply(0xc0011cf500, 0x1, 0xc00120bb58, 0xc000e698f0, 0x7cd3128, 0x0, 0x0)
        /go/src/github.com/cockroachdb/cockroach/vendor/github.com/cockroachdb/pebble/version_set.go:469 +0x1b3
github.com/cockroachdb/pebble.Open(0xc00086bc00, 0x19, 0xc00022f000, 0x0, 0x0, 0x0)
        /go/src/github.com/cockroachdb/cockroach/vendor/github.com/cockroachdb/pebble/open.go:358 +0x1396
github.com/cockroachdb/cockroach/pkg/storage.NewPebble(0x8d1c8d0, 0xc000e69500, 0x0, 0x0, 0x0, 0xc00086bc00, 0x19, 0x0, 0x0, 0x0, ...)
        /go/src/github.com/cockroachdb/cockroach/pkg/storage/pebble.go:697 +0x934
github.com/cockroachdb/cockroach/pkg/server.(*Config).CreateEngines(0xc0011cee00, 0x8d1c8d0, 0xc000e69500, 0x0, 0x0, 0x0, 0x0, 0x0)
        /go/src/github.com/cockroachdb/cockroach/pkg/server/config.go:584 +0x17b8
github.com/cockroachdb/cockroach/pkg/server.NewServer(0xc000cce000, 0xc0004489a0, 0xc000c75480, 0x0, 0x0, 0x0, 0x0, 0x1dcd6500, 0xc0008e04e0, 0x2d, ...)
        /go/src/github.com/cockroachdb/cockroach/pkg/server/server.go:290 +0x327
github.com/cockroachdb/cockroach/pkg/cli.runStart.func4.2(0xc000b34280, 0xc000264e38, 0xc000bfa090, 0x8d1c8d0, 0xc000e68060, 0x200, 0x1a2bc349, 0xeda122781, 0x0, 0x242, ...)
        /go/src/github.com/cockroachdb/cockroach/pkg/cli/start.go:626 +0x66
github.com/cockroachdb/cockroach/pkg/cli.runStart.func4(0xc000264e38, 0x8d1c8d0, 0xc000e68060, 0xc000c754c0, 0xc000b34280, 0xc000bfa090, 0x0, 0x1a2bc349, 0xeda122781, 0x0, ...)
        /go/src/github.com/cockroachdb/cockroach/pkg/cli/start.go:765 +0x12a
created by github.com/cockroachdb/cockroach/pkg/cli.runStart
```

Jira issue: PEBBLE-105

**Comment by jbowens** [comment]
Hi @gonzojive. The ‘invalid argument’ error string comes from the EINVAL errno returned by the operating system. I don’t think there’s any more context that Pebble can provide here. From Pebble’s perspective, an fsync failed and all the operating system provides is the errorno. I recommend digging into your environment’s diagnostics.

**Comment by jbowens** [comment]
Some potential action items here:

1. Massage `EINVAL` error messages into something that vaguely recommends the user check their filesystem environment.
2. Add additional documentation to CockroachDB docs about filesystem requirements and the errors encountered with certain misconfigurations.

**Comment by stevendanna** [comment]
@jbowens I suppose this is pretty old but github notified me so here I am.

It looks like this is from fsync() on a directory, I think it is relatively common to ignore EINVAL in that case.  A few years ago I did a quick survey that I summarized here:

https://github.com/habitat-sh/core/pull/120/commits/4129a6d843a28c01c6638a601cfef715dec8026a

My guess is if we wrapped that error just at the callsite where we sync on directories with something like "sync() on a directory appears unsupported on this filesystem" that would probably cover most of the cases we'll ever see EINVAL.
