### ISSUE TITLE
unexpected fault address 0x0

### ISSUE THREAD

**Issue by xkeyideal** [cockroachdb/pebble#1733]
```go
unexpected fault address 0x0
fatal error: fault
[signal SIGSEGV: segmentation violation code=0x80 addr=0x0 pc=0xdf08be]

goroutine 1027 [running]:
runtime.throw({0x11d5e51?, 0x4fd705?})
	/usr/local/opt/go/libexec/src/runtime/panic.go:992 +0x71 fp=0xc008a24a90 sp=0xc008a24a60 pc=0x434d11
runtime.sigpanic()
	/usr/local/opt/go/libexec/src/runtime/signal_unix.go:825 +0x305 fp=0xc008a24ae0 sp=0xc008a24a90 pc=0x44a385
encoding/binary.littleEndian.Uint32(...)
	/usr/local/opt/go/libexec/src/encoding/binary/binary.go:65
github.com/cockroachdb/pebble/sstable.(*blockIter).init(0xffffffffffffff11?, 0xc008a24b88?, {0x43a682009801cb02?, 0xc008478070?, 0xc00095ae63?}, 0xc008a24ba0?)
	/Users/wuzh/workspace/go/pkg/mod/github.com/cockroachdb/pebble@v0.0.0-20210331181633-27fc006b8bfb/sstable/block.go:256 +0x3e fp=0xc008a24b18 sp=0xc008a24ae0 pc=0xdf08be
github.com/cockroachdb/pebble/sstable.(*blockIter).initHandle(0xc002815b80?, 0xc0007d84a8?, {0x1?}, 0x0?)
	/Users/wuzh/workspace/go/pkg/mod/github.com/cockroachdb/pebble@v0.0.0-20210331181633-27fc006b8bfb/sstable/block.go:275 +0xd3 fp=0xc008a24b58 sp=0xc008a24b18 pc=0xdf0ad3
github.com/cockroachdb/pebble/sstable.(*singleLevelIterator).loadBlock(0xc008478000)
	/Users/wuzh/workspace/go/pkg/mod/github.com/cockroachdb/pebble@v0.0.0-20210331181633-27fc006b8bfb/sstable/reader.go:217 +0x186 fp=0xc008a24b98 sp=0xc008a24b58 pc=0xdf7706
github.com/cockroachdb/pebble/sstable.(*singleLevelIterator).SeekGE(0xc008478000, {0xc008a136c0, 0x63, 0x70})
	/Users/wuzh/workspace/go/pkg/mod/github.com/cockroachdb/pebble@v0.0.0-20210331181633-27fc006b8bfb/sstable/reader.go:256 +0xe9 fp=0xc008a24bf8 sp=0xc008a24b98 pc=0xdf7869
github.com/cockroachdb/pebble.(*levelIter).SeekGE(0xc008a365f0, {0xc008a136c0, 0x63, 0x70})
	/Users/wuzh/workspace/go/pkg/mod/github.com/cockroachdb/pebble@v0.0.0-20210331181633-27fc006b8bfb/level_iter.go:348 +0xb1 fp=0xc008a24c28 sp=0xc008a24bf8 pc=0xe4adf1
github.com/cockroachdb/pebble.(*getIter).Next(0xc008a36550)
	/Users/wuzh/workspace/go/pkg/mod/github.com/cockroachdb/pebble@v0.0.0-20210331181633-27fc006b8bfb/get_iter.go:170 +0xd28 fp=0xc008a25038 sp=0xc008a24c28 pc=0xe3c3e8
github.com/cockroachdb/pebble.(*getIter).First(0x40d687?)
	/Users/wuzh/workspace/go/pkg/mod/github.com/cockroachdb/pebble@v0.0.0-20210331181633-27fc006b8bfb/get_iter.go:60 +0x19 fp=0xc008a25050 sp=0xc008a25038 pc=0xe3b659
github.com/cockroachdb/pebble.(*Iterator).First(0xc008a36400)
	/Users/wuzh/workspace/go/pkg/mod/github.com/cockroachdb/pebble@v0.0.0-20210331181633-27fc006b8bfb/iterator.go:401 +0x10a fp=0xc008a25080 sp=0xc008a25050 pc=0xe434aa
github.com/cockroachdb/pebble.(*DB).getInternal(0xc007905500, {0xc008a136c0, 0x63, 0x70}, 0x0, 0x0)
	/Users/wuzh/workspace/go/pkg/mod/github.com/cockroachdb/pebble@v0.0.0-20210331181633-27fc006b8bfb/db.go:413 +0x368 fp=0xc008a250c8 sp=0xc008a25080 pc=0xe2f908
github.com/cockroachdb/pebble.(*DB).Get(...)
	/Users/wuzh/workspace/go/pkg/mod/github.com/cockroachdb/pebble@v0.0.0-20210331181633-27fc006b8bfb/db.go:356
rubik-center/raft/store.(*Store).GetBytes(0x1066720?, {0xc008a136c0?, 0xc0005323c8?, 0x5?})
	/Users/wuzh/workspace/rubik/flight.rubik.center/raft/store/store.go:52 +0x2e fp=0xc008a25140 sp=0xc008a250c8 pc=0xe7472e
rubik-center/raft/command.(*TryUnlockCommand).LocalInvoke(0xc001af2700, 0xc0029e77a0, {0x6c?, 0x7f7525fd6910?, 0x30?})
	/Users/wuzh/workspace/rubik/flight.rubik.center/raft/command/try_unLock.go:43 +0x1d5 fp=0xc008a25200 sp=0xc008a25140 pc=0xf1b395
rubik-center/raft.(*StateMachine).processEntry(0xc001e1c8d0, {0xef6, {0xc008a135e0, 0x6c, 0x6c}, {0x0, {0x0, 0x0, 0x0}}})
	/Users/wuzh/workspace/rubik/flight.rubik.center/raft/state_machine.go:97 +0x12d fp=0xc008a25290 sp=0xc008a25200 pc=0xf2526d
rubik-center/raft.(*StateMachine).Update(0xc001e1c8d0, {0xc00095f2c0, 0x1, 0x6f?})
	/Users/wuzh/workspace/rubik/flight.rubik.center/raft/state_machine.go:62 +0x40e fp=0xc008a25478 sp=0xc008a25290 pc=0xf24e6e
github.com/lni/dragonboat/v3/internal/rsm.(*OnDiskStateMachine).Update(0xc008a254e8?, {0xc00095f2c0?, 0xc008a0c9a0?, 0x64?})
	/Users/wuzh/workspace/go/pkg/mod/github.com/xkeyideal/dragonboat/v3@v3.3.5-pd/internal/rsm/adapter.go:295 +0x2c fp=0xc008a254a8 sp=0xc008a25478 pc=0xea050c
github.com/lni/dragonboat/v3/internal/rsm.(*NativeSM).Update(0xc00065c1a0, {0xef6, {0xc008a135e0, 0x6c, 0x6c}, {0x0, {0x0, 0x0, 0x0}}})
	/Users/wuzh/workspace/go/pkg/mod/github.com/xkeyideal/dragonboat/v3@v3.3.5-pd/internal/rsm/managed.go:182 +0xdb fp=0xc008a254f8 sp=0xc008a254a8 pc=0xea3ddb
github.com/lni/dragonboat/v3/internal/rsm.(*StateMachine).update(0xc007d203c0, {0x24, 0xef6, 0x2, 0x31c615fc4eb5cfbf, 0xb3bffac6a9a34f66, 0x0, 0x0, {0xc008a0c9a0, 0x64, ...}})
	/Users/wuzh/workspace/go/pkg/mod/github.com/xkeyideal/dragonboat/v3@v3.3.5-pd/internal/rsm/statemachine.go:1034 +0x34d fp=0xc008a256a8 sp=0xc008a254f8 pc=0xeb890d
github.com/lni/dragonboat/v3/internal/rsm.(*StateMachine).handleEntry(0xc007d203c0, {0x24, 0xef6, 0x2, 0x31c615fc4eb5cfbf, 0xb3bffac6a9a34f66, 0x0, 0x0, {0xc008a0c9a0, 0x64, ...}}, ...)
	/Users/wuzh/workspace/go/pkg/mod/github.com/xkeyideal/dragonboat/v3@v3.3.5-pd/internal/rsm/statemachine.go:897 +0x2f8 fp=0xc008a25740 sp=0xc008a256a8 pc=0xeb71f8
github.com/lni/dragonboat/v3/internal/rsm.(*StateMachine).handle(0xc007d203c0, {0xc001ae4000, 0x1, 0x0?}, {0xc001c02000, 0x0, 0x200})
	/Users/wuzh/workspace/go/pkg/mod/github.com/xkeyideal/dragonboat/v3@v3.3.5-pd/internal/rsm/statemachine.go:840 +0x367 fp=0xc008a25850 sp=0xc008a25740 pc=0xeb6c47
github.com/lni/dragonboat/v3/internal/rsm.(*StateMachine).Handle(0xc007d203c0, {0xc001ae4000, 0xc00285ad20?, 0x200}, {0xc001c02000, 0x0?, 0x200})
	/Users/wuzh/workspace/go/pkg/mod/github.com/xkeyideal/dragonboat/v3@v3.3.5-pd/internal/rsm/statemachine.go:592 +0x3eb fp=0xc008a25a88 sp=0xc008a25850 pc=0xeb2ecb
github.com/lni/dragonboat/v3.(*node).handleTask(...)
	/Users/wuzh/workspace/go/pkg/mod/github.com/xkeyideal/dragonboat/v3@v3.3.5-pd/node.go:861
github.com/lni/dragonboat/v3.(*engine).processApplies(0xc00127f050?, 0xc001db2dc0?, 0x0?, {0xc001ae4000, 0x0, 0x200}, {0xc001c02000, 0x0, 0x200})
	/Users/wuzh/workspace/go/pkg/mod/github.com/xkeyideal/dragonboat/v3@v3.3.5-pd/engine.go:1183 +0x237 fp=0xc008a25d40 sp=0xc008a25a88 pc=0xeef7b7
github.com/lni/dragonboat/v3.(*engine).applyWorkerMain(0xc00038c640, 0xe)
	/Users/wuzh/workspace/go/pkg/mod/github.com/xkeyideal/dragonboat/v3@v3.3.5-pd/engine.go:1150 +0x317 fp=0xc008a25f40 sp=0xc008a25d40 pc=0xeef1f7
github.com/lni/dragonboat/v3.newExecEngine.func3()
	/Users/wuzh/workspace/go/pkg/mod/github.com/xkeyideal/dragonboat/v3@v3.3.5-pd/engine.go:1031 +0x25 fp=0xc008a25f60 sp=0xc008a25f40 pc=0xeee425
github.com/lni/goutils/syncutil.(*Stopper).runWorker.func1()
	/Users/wuzh/workspace/go/pkg/mod/github.com/lni/goutils@v1.3.0/syncutil/stopper.go:79 +0xc5 fp=0xc008a25fe0 sp=0xc008a25f60 pc=0xa96ee5
runtime.goexit()
	/usr/local/opt/go/libexec/src/runtime/asm_amd64.s:1571 +0x1 fp=0xc008a25fe8 sp=0xc008a25fe0 pc=0x464ce1
created by github.com/lni/goutils/syncutil.(*Stopper).runWorker
	/Users/wuzh/workspace/go/pkg/mod/github.com/lni/goutils@v1.3.0/syncutil/stopper.go:74 +0xea
```

**Comment by xkeyideal** [comment]
I use [dragonboat](https://github.com/lni/dragonboat/tree/v3.3.5) framework, it use the version of Pebble(27fc006b8bfb), so I can't upgrade Pebble version.

The question caused by cross compile on MacOS. I compile my program on linux and run it maybe have no problem yestoday.

I will check it again today.

**Comment by xkeyideal** [comment]
Concluded after two days of tests, the question caused by cross compile on MacOS.
