### ISSUE TITLE
compaction: panic due to index out of bounds

### ISSUE THREAD

**Issue by nicktrav** [cockroachdb/pebble#1781]
I noticed this while investigating cockroachdb/cockroach#82924.

Node 3 crashed with the following:

```console
panic: runtime error: index out of range [2] with length 2

goroutine 171900 [running]:
panic({0x4cc5e40, 0xc00a25ccd8})
        GOROOT/src/runtime/panic.go:1147 +0x3a8 fp=0xc005ba5590 sp=0xc005ba54d0 pc=0x48a828
runtime.goPanicIndex(0x2, 0x2)
        GOROOT/src/runtime/panic.go:90 +0x75 fp=0xc005ba55d0 sp=0xc005ba5590 pc=0x487bb5
github.com/cockroachdb/pebble/internal/manifest.(*L0Sublevels).InitCompactingFileInfo(0xc00509b170, {0xc003c08b40, 0x1, 0xc00503c510})
        github.com/cockroachdb/pebble/internal/manifest/external/com_github_cockroachdb_pebble/internal/manifest/l0_sublevels.go:721 +0x4be fp=0xc005ba5850 sp=0xc005ba55d0 pc=0x10bf8fe
github.com/cockroachdb/pebble.(*DB).removeInProgressCompaction(0xc000b47200, 0xc00194bb00)
        github.com/cockroachdb/pebble/external/com_github_cockroachdb_pebble/compaction.go:1200 +0xb7 fp=0xc005ba5be0 sp=0xc005ba5850 pc=0x114b457
github.com/cockroachdb/pebble.(*DB).compact1(0xc000b47200, 0xc00194bb00, 0x0)
        github.com/cockroachdb/pebble/external/com_github_cockroachdb_pebble/compaction.go:1904 +0x5ef fp=0xc005ba5e80 sp=0xc005ba5be0 pc=0x115028f
github.com/cockroachdb/pebble.(*DB).compact.func1({0x66a5bd8, 0xc005cec2d0})
        github.com/cockroachdb/pebble/external/com_github_cockroachdb_pebble/compaction.go:1840 +0xad fp=0xc005ba5ee8 sp=0xc005ba5e80 pc=0x114fbad
runtime/pprof.Do({0x66a5b68, 0xc000076088}, {{0xc0000cee40, 0x1074827b0, 0xc001d3e7d0}}, 0xc007482788)
        GOROOT/src/runtime/pprof/runtime.go:40 +0xa3 fp=0xc005ba5f58 sp=0xc005ba5ee8 pc=0x1027ba3
github.com/cockroachdb/pebble.(*DB).compact(0xc0074827d0, 0x11248c6, 0xc001d3e7c0)
        github.com/cockroachdb/pebble/external/com_github_cockroachdb_pebble/compaction.go:1837 +0x6b fp=0xc005ba5fb8 sp=0xc005ba5f58 pc=0x114facb
github.com/cockroachdb/pebble.(*DB).maybeScheduleCompactionPicker·dwrap·13()
        github.com/cockroachdb/pebble/external/com_github_cockroachdb_pebble/compaction.go:1631 +0x2e fp=0xc005ba5fe0 sp=0xc005ba5fb8 pc=0x114e38e
runtime.goexit()
        GOROOT/src/runtime/asm_amd64.s:1581 +0x1 fp=0xc005ba5fe8 sp=0xc005ba5fe0 pc=0x4bf321
created by github.com/cockroachdb/pebble.(*DB).maybeScheduleCompactionPicker
        github.com/cockroachdb/pebble/external/com_github_cockroachdb_pebble/compaction.go:1631 +0x5c5
```

Node 3 also had a bad block device, so this may have contributed.

Running with Pebble version ad44a62e4d04.

**Comment by nicktrav** [comment]
One avenue I am going to pursue is to stress test the behavior when compactions cannot proceed (e.g. due to FS issues), as was the case with the clearrange failure.
