### ISSUE TITLE
db: TestDBConcurrentCompactClose is flaky

### ISSUE THREAD

**Issue by nicktrav** [cockroachdb/pebble#1833]
See https://github.com/cockroachdb/pebble/runs/7583177960?check_suite_focus=true

**Comment by nicktrav** [comment]
This reproduces for me on macOS:

```console
$ go test -mod=vendor -tags 'invariants'  -run TestDBConcurrentCompactClose -count 10 .
--- FAIL: TestDBConcurrentCompactClose (0.00s)
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x258 pc=0x4363023]

goroutine 31004 [running]:
github.com/cockroachdb/pebble/internal/cache.(*robinHoodMap).Get(0x4098b91?, {{0x0?, 0x1e14?}, 0x2?})
        /Users/nickt/Development/pebble/internal/cache/robin_hood.go:248 +0x63
github.com/cockroachdb/pebble/internal/cache.(*shard).EvictFile(0xc0002c7500, 0x40?, 0xa0?)
        /Users/nickt/Development/pebble/internal/cache/clockpro.go:254 +0x90
github.com/cockroachdb/pebble/internal/cache.(*Cache).EvictFile(...)
        /Users/nickt/Development/pebble/internal/cache/clockpro.go:764
github.com/cockroachdb/pebble.(*tableCacheShard).evict(0xc000433900, 0x18, 0xc0005b2c08, 0x0)
        /Users/nickt/Development/pebble/table_cache.go:778 +0x2ae
github.com/cockroachdb/pebble.(*tableCacheContainer).evict(...)
        /Users/nickt/Development/pebble/table_cache.go:152
github.com/cockroachdb/pebble.(*DB).doDeleteObsoleteFiles(0xc000489b00, 0x8)
        /Users/nickt/Development/pebble/compaction.go:2985 +0xa05
github.com/cockroachdb/pebble.(*DB).deleteObsoleteFiles(0xc000489b00, 0xc00023c8b0?, 0x7?)
        /Users/nickt/Development/pebble/compaction.go:2884 +0x38
github.com/cockroachdb/pebble.(*DB).compact1(0xc000489b00, 0xc0003e7b00, 0x0)
        /Users/nickt/Development/pebble/compaction.go:2116 +0x615
github.com/cockroachdb/pebble.(*DB).compact.func1({0x47cb130, 0xc000751d10})
        /Users/nickt/Development/pebble/compaction.go:2047 +0xad
runtime/pprof.Do({0x47cb0c0?, 0xc00019c008?}, {{0xc0001ec6a0?, 0x10046d7b0?, 0xc00056c550?}}, 0xc00046d788)
        /nix/store/18qwv5zrbv33xwmkh42xaww4v2as6gd3-go-1.18.2/share/go/src/runtime/pprof/runtime.go:40 +0xa3
github.com/cockroachdb/pebble.(*DB).compact(0xc00046d7d0?, 0x438e446?, 0xc00056c540?)
        /Users/nickt/Development/pebble/compaction.go:2044 +0x6b
created by github.com/cockroachdb/pebble.(*DB).maybeScheduleCompactionPicker
        /Users/nickt/Development/pebble/compaction.go:1765 +0x5d6
FAIL    github.com/cockroachdb/pebble   1.332s
FAIL
```

Another example:

```console
$ go test -mod=vendor -tags 'invariants'  -run TestDBConcurrentCompactClose -count 10 .
--- FAIL: TestDBConcurrentCompactClose (0.00s)
panic: assignment to entry in nil map

goroutine 30986 [running]:
github.com/cockroachdb/pebble.(*tableCacheShard).addNode(0xc000276dc0, 0xc000577890, 0xc000038508)
        /Users/nickt/Development/pebble/table_cache.go:656 +0x85
github.com/cockroachdb/pebble.(*tableCacheShard).findNode(0xc000276dc0, 0xc000447b80, 0xc000038508)
        /Users/nickt/Development/pebble/table_cache.go:592 +0x2c6
github.com/cockroachdb/pebble.(*tableCacheShard).newIters(0xc000276dc0, 0x1000?, 0xc0002c4050, 0xc00063cdb0, 0xc000038508)
        /Users/nickt/Development/pebble/table_cache.go:361 +0x85
github.com/cockroachdb/pebble.(*tableCacheContainer).newIters(0x0?, 0x8?, 0x10?, 0x0?)
        /Users/nickt/Development/pebble/table_cache.go:138 +0x45
github.com/cockroachdb/pebble.(*levelIter).loadFile(0xc0002c4000, 0xc000447b80, 0x1)
        /Users/nickt/Development/pebble/level_iter.go:566 +0x28f
github.com/cockroachdb/pebble.(*levelIter).First(0xc0002c4000)
        /Users/nickt/Development/pebble/level_iter.go:730 +0x88
github.com/cockroachdb/pebble.(*mergingIter).First(0xc0000eed00)
        /Users/nickt/Development/pebble/merging_iter.go:1062 +0xce
github.com/cockroachdb/pebble.(*compactionIter).First(0xc000146a80)
        /Users/nickt/Development/pebble/compaction_iter.go:255 +0x3c
github.com/cockroachdb/pebble.(*DB).runCompaction(0xc000601200, 0x9, 0xc00063cd00)
        /Users/nickt/Development/pebble/compaction.go:2582 +0x1b6e
github.com/cockroachdb/pebble.(*DB).compact1(0xc000601200, 0xc00063cd00, 0x0)
        /Users/nickt/Development/pebble/compaction.go:2076 +0x1a5
github.com/cockroachdb/pebble.(*DB).compact.func1({0x47cb130, 0xc000577770})
        /Users/nickt/Development/pebble/compaction.go:2047 +0xad
runtime/pprof.Do({0x47cb0c0?, 0xc00002a0d0?}, {{0xc0000886c0?, 0x10022b7b0?, 0xc00009bc90?}}, 0xc00022b788)
        /nix/store/18qwv5zrbv33xwmkh42xaww4v2as6gd3-go-1.18.2/share/go/src/runtime/pprof/runtime.go:40 +0xa3
github.com/cockroachdb/pebble.(*DB).compact(0xc00022b7d0?, 0x438e446?, 0xc00009bc80?)
        /Users/nickt/Development/pebble/compaction.go:2044 +0x6b
created by github.com/cockroachdb/pebble.(*DB).maybeScheduleCompactionPicker
        /Users/nickt/Development/pebble/compaction.go:1765 +0x5d6
FAIL    github.com/cockroachdb/pebble   1.451s
FAIL

```

This also fais on Linux:

```console
--- FAIL: TestDBConcurrentCompactClose (0.03s)
fatal error: checkptr: pointer arithmetic computed bad pointer value

goroutine 30877 [running]:
runtime.throw({0xe1f640?, 0x48987c?})
        /nix/store/x41pvzhr1x20wfhl4rczyb23zrsrv9bh-go-1.18.2/share/go/src/runtime/panic.go:992 +0x71 fp=0xc00014d2b0 sp=0xc00014d280 pc=0x451ad1
runtime.checkptrArithmetic(0xcedf20?, {0xc00014d350?, 0xc0003e3a98?, 0x0?})
        /nix/store/x41pvzhr1x20wfhl4rczyb23zrsrv9bh-go-1.18.2/share/go/src/runtime/checkptr.go:52 +0xbb fp=0xc00014d2e0 sp=0xc00014d2b0 pc=0x42255b
github.com/cockroachdb/pebble/internal/cache.robinHoodEntries.at(...)
        /home/nickt/Development/pebble/internal/cache/robin_hood.go:67
github.com/cockroachdb/pebble/internal/cache.(*robinHoodMap).Get(0xc0003e3ae0, {{0x463895?, 0xcf67e0?}, 0x48848c?})
        /home/nickt/Development/pebble/internal/cache/robin_hood.go:247 +0x132 fp=0xc00014d368 sp=0xc00014d2e0 pc=0x954532
github.com/cockroachdb/pebble/internal/cache.(*shard).EvictFile(0xc0003e3a80, 0x0?, 0x3?)
        /home/nickt/Development/pebble/internal/cache/clockpro.go:254 +0xc6 fp=0xc00014d418 sp=0xc00014d368 pc=0x94e126
github.com/cockroachdb/pebble/internal/cache.(*Cache).EvictFile(...)
        /home/nickt/Development/pebble/internal/cache/clockpro.go:764
github.com/cockroachdb/pebble.(*tableCacheShard).evict(0xc00044a280, 0x17, 0xc000512c08, 0x0)
        /home/nickt/Development/pebble/table_cache.go:778 +0x3e8 fp=0xc00014d4e0 sp=0xc00014d418 pc=0xad5988
github.com/cockroachdb/pebble.(*tableCacheContainer).evict(...)
        /home/nickt/Development/pebble/table_cache.go:152
github.com/cockroachdb/pebble.(*DB).doDeleteObsoleteFiles(0xc000204d80, 0x9)
        /home/nickt/Development/pebble/compaction.go:2985 +0xffc fp=0xc00014d918 sp=0xc00014d4e0 pc=0xa3ab9c
github.com/cockroachdb/pebble.(*DB).deleteObsoleteFiles(0xc000204d80, 0xc000080740?, 0x1?)
        /home/nickt/Development/pebble/compaction.go:2884 +0x53 fp=0xc00014d948 sp=0xc00014d918 pc=0xa39b13
github.com/cockroachdb/pebble.(*DB).compact1(0xc000204d80, 0xc0005b2d00, 0x0)
        /home/nickt/Development/pebble/compaction.go:2116 +0xb18 fp=0xc00014ddc0 sp=0xc00014d948 pc=0xa2ea78
github.com/cockroachdb/pebble.(*DB).compact.func1({0xf39278, 0xc000525440})
        /home/nickt/Development/pebble/compaction.go:2047 +0xd3 fp=0xc00014de88 sp=0xc00014ddc0 pc=0xa2ddb3
runtime/pprof.Do({0xf39208, 0xc0000240e8}, {{0xc00008a680?, 0xc0006747d0?, 0x4897c5?}}, 0xc000218f78)
        /nix/store/x41pvzhr1x20wfhl4rczyb23zrsrv9bh-go-1.18.2/share/go/src/runtime/pprof/runtime.go:40 +0x123 fp=0xc00014df40 sp=0xc00014de88 pc=0x67d583
github.com/cockroachdb/pebble.(*DB).compact(0xc000204d80, 0xc0005b2d00, 0x0)
        /home/nickt/Development/pebble/compaction.go:2044 +0xb6 fp=0xc00014dfa8 sp=0xc00014df40 pc=0xa2dc96
github.com/cockroachdb/pebble.(*DB).maybeScheduleCompactionPicker.func4()
        /home/nickt/Development/pebble/compaction.go:1765 +0x4a fp=0xc00014dfe0 sp=0xc00014dfa8 pc=0xa2ba4a
runtime.goexit()
        /nix/store/x41pvzhr1x20wfhl4rczyb23zrsrv9bh-go-1.18.2/share/go/src/runtime/asm_amd64.s:1571 +0x1 fp=0xc00014dfe8 sp=0xc00014dfe0 pc=0x486901
created by github.com/cockroachdb/pebble.(*DB).maybeScheduleCompactionPicker
        /home/nickt/Development/pebble/compaction.go:1765 +0x10bf
```

**Comment by nicktrav** [comment]
Actually - false alarm.
