### ISSUE TITLE
crl-release-22.1: nil pointer dereference

### ISSUE THREAD

**Issue by jbowens** [cockroachdb/pebble#2011]
It appears to be possible to construct a database with 21.2 (36e8e921) that causes 22.1 (b66ae1e4) to panic with a nil pointer dereference on open. It appears as though L0Sublevels doesn't exist. If I recall correctly, that at least one point could happen if a compaction errored out. Did we forget to backport that? If so, it's also unclear why the compaction failed. Unfortunately, we don't have any of the EventListener logs here. I'll add that to the crossversion test.

```
    crossversion_test.go:72: Test directory: /tmp/TestMetaCrossVersion2746937505/001
    crossversion_test.go:73: Reproduction:
          go test -v -run 'TestMetaCrossVersion' --seed 1665774008718434026 --factor 10 --version 21.2,36e8e921,/home/jackson/go/src/github.com/cockroachdb/pebble/meta.21.2.test --version 22.1,b66ae1e4,/home/jackson/go/src/github.com/cockroachdb/pebble/meta.22.1.test --version 22.2,8f2c02f5,/home/jackson/go/src/github.com/cockroachdb/pebble/meta.22.2.test --version master,eec7375f,/home/jackson/go/src/github.com/cockroachdb/pebble/meta.master.test

    crossversion_test.go:85: 0: 21.2,36e8e921,/home/jackson/go/src/github.com/cockroachdb/pebble/meta.21.2.test
    crossversion_test.go:85: 1: 22.1,b66ae1e4,/home/jackson/go/src/github.com/cockroachdb/pebble/meta.22.1.test
    crossversion_test.go:85: 2: 22.2,8f2c02f5,/home/jackson/go/src/github.com/cockroachdb/pebble/meta.22.2.test
    crossversion_test.go:85: 3: master,eec7375f,/home/jackson/go/src/github.com/cockroachdb/pebble/meta.master.test
    crossversion_test.go:139: Running tests with version 36e8e921 with 1 initial state(s).
    crossversion_test.go:145:   Running test with version 36e8e921 with initial state <empty>.
    crossversion_test.go:139: Running tests with version b66ae1e4 with 10 initial state(s).
    crossversion_test.go:145:   Running test with version b66ae1e4 with initial state sha=36e8e921-seed=11375172571715449164-opts=standard-005(<empty>).
    crossversion_test.go:145:   Running test with version b66ae1e4 with initial state sha=36e8e921-seed=11375172571715449164-opts=random-020(<empty>).
    crossversion_test.go:145:   Running test with version b66ae1e4 with initial state sha=36e8e921-seed=11375172571715449164-opts=standard-008(<empty>).
    crossversion_test.go:145:   Running test with version b66ae1e4 with initial state sha=36e8e921-seed=11375172571715449164-opts=random-003(<empty>).
    crossversion_test.go:161: Metamorphic test failed: exit status 1
        Output:--- FAIL: TestMeta (1.29s)
            --- FAIL: TestMeta/standard-000 (0.02s)
                meta_test.go:352:
                    ===== SEED =====
                    10858758592825965365
                    ===== ERR =====
                    exit status 2
                    ===== OUT =====
                    --- FAIL: TestMeta (0.01s)
                    panic: runtime error: invalid memory address or nil pointer dereference [recovered]
                        panic: runtime error: invalid memory address or nil pointer dereference [recovered]
                        panic: runtime error: invalid memory address or nil pointer dereference
                    [signal SIGSEGV: segmentation violation code=0x1 addr=0x58 pc=0x773511]

                    goroutine 19 [running]:
                    testing.tRunner.func1.2({0x96ab20, 0xf73d70})
                        /usr/local/go/src/testing/testing.go:1396 +0x24e
                    testing.tRunner.func1()
                        /usr/local/go/src/testing/testing.go:1399 +0x39f
                    panic({0x96ab20, 0xf73d70})
                        /usr/local/go/src/runtime/panic.go:884 +0x212
                    github.com/cockroachdb/pebble.Open.func1()
                        /home/jackson/go/src/github.com/cockroachdb/pebble/open.go:112 +0x175
                    panic({0x96ab20, 0xf73d70})
                        /usr/local/go/src/runtime/panic.go:890 +0x262
                    github.com/cockroachdb/pebble/internal/manifest.(*L0Sublevels).InUseKeyRanges(0x0, {0x0?, 0x0?, 0x0?}, {0x0, 0x0, 0x0})
                        /home/jackson/go/src/github.com/cockroachdb/pebble/internal/manifest/l0_sublevels.go:887 +0x51
                    github.com/cockroachdb/pebble.calculateInuseKeyRanges(0xc00017a140, 0xa25dc0, 0xc000181c80?, 0x6, {0x0, 0x0, 0x0}, {0x0, 0x0, 0x0})
                        /home/jackson/go/src/github.com/cockroachdb/pebble/compaction.go:664 +0x95
                    github.com/cockroachdb/pebble.(*compaction).setupInuseKeyRanges(0xc00016a580)
                        /home/jackson/go/src/github.com/cockroachdb/pebble/compaction.go:648 +0x85
                    github.com/cockroachdb/pebble.newFlush(0xc000004280, 0xc00017a140, 0x34?, {0x0, 0x0, 0x0}, 0xc00016e010)
                        /home/jackson/go/src/github.com/cockroachdb/pebble/compaction.go:639 +0x72a
```

```
                    ===== HISTORY =====
                    // INFO: [JOB 1] MANIFEST created 000001
                    // INFO: upgraded to format version: 002
                    // INFO: upgraded to format version: 003
                    // INFO: upgraded to format version: 004
                    // INFO: upgraded to format version: 005
```

**Comment by jbowens** [comment]
> ```
>                     // INFO: [JOB 1] MANIFEST created 000001
> ```

That seems suspicious. The manifest should not have file number 000001 if we're opening an existing database.

**Comment by itsbilal** [comment]
Found the bug; it happens any time when the initial state contains a separate WAL directory, but the new state does not. The logic in `setupInitialState` in the crossversion test is slightly broken and doesn't successfully copy over the WAL directory. I'll put out a fix soon.

**Comment by itsbilal** [comment]
However, it's probably also a bug that we can't successfully do a flush without a panic if the starting state has a WAL but no manifest (which is what was happening due to the `setupInitialState` bug). Taking a look at that as well.
