### ISSUE TITLE
replay: WorkloadCollector file removal race

### ISSUE THREAD

**Issue by jbowens** [cockroachdb/pebble#2221]
There appears to be a race in the workload collector:
```
panic: remove 023115.sst: no such file or directory

goroutine 63177 [running]:
panic({0x511b7c0, 0xc01a55bcf8})
        GOROOT/src/runtime/panic.go:987 +0x3ba fp=0xc0004b5e88 sp=0xc0004b5dc8 pc=0x48d7fa
github.com/cockroachdb/pebble/replay.(*WorkloadCollector).processSSTables(0xc000be3000, {0xc01b8aff00, 0x6, 0x8})
        github.com/cockroachdb/pebble/replay/external/com_github_cockroachdb_pebble/replay/workload_capture.go:327 +0x312 fp=0xc0004b5f58 sp=0xc0004b5e88 pc=0x18c3d32
github.com/cockroachdb/pebble/replay.(*WorkloadCollector).filesToProcessWatcher(0xc000be3000)
        github.com/cockroachdb/pebble/replay/external/com_github_cockroachdb_pebble/replay/workload_capture.go:236 +0x1c5 fp=0xc0004b5fc8 sp=0xc0004b5f58 pc=0x18c34e5
github.com/cockroachdb/pebble/replay.(*WorkloadCollector).Start.func1()
        github.com/cockroachdb/pebble/replay/external/com_github_cockroachdb_pebble/replay/workload_capture.go:356 +0x26 fp=0xc0004b5fe0 sp=0xc0004b5fc8 pc=0x18c4266
runtime.goexit()
        GOROOT/src/runtime/asm_amd64.s:1594 +0x1 fp=0xc0004b5fe8 sp=0xc0004b5fe0 pc=0x4c24e1
created by github.com/cockroachdb/pebble/replay.(*WorkloadCollector).Start
        github.com/cockroachdb/pebble/replay/external/com_github_cockroachdb_pebble/replay/workload_capture.go:356 +0x2c5
```

**Comment by nicktrav** [comment]
Do you have the repro steps for this one? I tried `-race` on the `replay` package, but I couldn't get it to fail (with `stress`).

**Comment by jbowens** [comment]
This isn't a data race. I think it's a race in the lifecycle of a file in the workload collector that results in attempting to remove a file twice. The above stack trace is from an attempt to collect a tpcc workload.
