### ISSUE TITLE
db:  allocation failed because arena is full

### ISSUE THREAD

**Issue by jbowens** [cockroachdb/pebble#2516]
Observed [here](https://teamcity.cockroachdb.com/viewLog.html?buildId=9990052&tab=buildResultsDiv&buildTypeId=Cockroach_UnitTests_BazelUnitTests) in CI for cockroachdb/cockroach#102877.

```
=== RUN   TestCCLLogic_regional_by_row_rename_column
    test_log_scope.go:161: test logs captured to: /artifacts/tmp/_tmp/24b232bb2ddb5cbd23310506078b09b9/logTestCCLLogic_regional_by_row_rename_column1468365075
    test_log_scope.go:79: use -show-logs to present logs inline
F230508 22:22:00.549432 9359 3@pebble/db.go:811  [n5,s5,pebble] 1  pebble: fatal commit error: allocation failed because arena is full
F230508 22:22:00.549432 9359 3@pebble/db.go:811  [n5,s5,pebble] 1 !goroutine 9359 [running]:
F230508 22:22:00.549432 9359 3@pebble/db.go:811  [n5,s5,pebble] 1 !github.com/cockroachdb/cockroach/pkg/util/log.getStacks(0x0)
F230508 22:22:00.549432 9359 3@pebble/db.go:811  [n5,s5,pebble] 1 !	github.com/cockroachdb/cockroach/pkg/util/log/get_stacks.go:25 +0x89
F230508 22:22:00.549432 9359 3@pebble/db.go:811  [n5,s5,pebble] 1 !github.com/cockroachdb/cockroach/pkg/util/log.(*loggerT).outputLogEntry(0xc001029fe0, {{{0x0, 0x0}, {0x0, 0x0}, {0x0, 0x0}, {0x0, 0x0}}, 0x175d4b3390b1fb7d, ...})
F230508 22:22:00.549432 9359 3@pebble/db.go:811  [n5,s5,pebble] 1 !	github.com/cockroachdb/cockroach/pkg/util/log/clog.go:260 +0xb8
F230508 22:22:00.549432 9359 3@pebble/db.go:811  [n5,s5,pebble] 1 !github.com/cockroachdb/cockroach/pkg/util/log.logfDepthInternal({0x70f1a38, 0xc00479e030}, 0x3, 0x4, 0x3, 0x0?, {0x5bd4333, 0x1e}, {0xc0038a0e80, 0x1, ...})
F230508 22:22:00.549432 9359 3@pebble/db.go:811  [n5,s5,pebble] 1 !	github.com/cockroachdb/cockroach/pkg/util/log/channels.go:106 +0x645
F230508 22:22:00.549432 9359 3@pebble/db.go:811  [n5,s5,pebble] 1 !github.com/cockroachdb/cockroach/pkg/util/log.logfDepth(...)
F230508 22:22:00.549432 9359 3@pebble/db.go:811  [n5,s5,pebble] 1 !	github.com/cockroachdb/cockroach/pkg/util/log/channels.go:39
F230508 22:22:00.549432 9359 3@pebble/db.go:811  [n5,s5,pebble] 1 !github.com/cockroachdb/cockroach/pkg/util/log.loggerStorage.FatalfDepth(...)
F230508 22:22:00.549432 9359 3@pebble/db.go:811  [n5,s5,pebble] 1 !	github.com/cockroachdb/cockroach/bazel-out/k8-fastbuild/bin/pkg/util/log/log_channels_generated.go:2223
F230508 22:22:00.549432 9359 3@pebble/db.go:811  [n5,s5,pebble] 1 !github.com/cockroachdb/cockroach/pkg/storage.pebbleLogger.Fatalf({{0x70f1a38?, 0xc00479e030?}, 0x12ad527?}, {0x5bd4333?, 0x463207?}, {0xc0038a0e80?, 0x5104180?, 0x1?})
F230508 22:22:00.549432 9359 3@pebble/db.go:811  [n5,s5,pebble] 1 !	github.com/cockroachdb/cockroach/pkg/storage/pebble.go:687 +0x56
F230508 22:22:00.549432 9359 3@pebble/db.go:811  [n5,s5,pebble] 1 !github.com/cockroachdb/pebble.(*DB).applyInternal(0xc004b5b400, 0xc010224640, 0x1a5f2dd?, 0xd7?)
F230508 22:22:00.549432 9359 3@pebble/db.go:811  [n5,s5,pebble] 1 !	github.com/cockroachdb/pebble/external/com_github_cockroachdb_pebble/db.go:811 +0x278
F230508 22:22:00.549432 9359 3@pebble/db.go:811  [n5,s5,pebble] 1 !github.com/cockroachdb/pebble.(*DB).Apply(...)
F230508 22:22:00.549432 9359 3@pebble/db.go:811  [n5,s5,pebble] 1 !	github.com/cockroachdb/pebble/external/com_github_cockroachdb_pebble/db.go:746
F230508 22:22:00.549432 9359 3@pebble/db.go:811  [n5,s5,pebble] 1 !github.com/cockroachdb/pebble.(*Batch).Commit(...)
F230508 22:22:00.549432 9359 3@pebble/db.go:811  [n5,s5,pebble] 1 !	github.com/cockroachdb/pebble/external/com_github_cockroachdb_pebble/batch.go:1109
F230508 22:22:00.549432 9359 3@pebble/db.go:811  [n5,s5,pebble] 1 !github.com/cockroachdb/cockroach/pkg/storage.(*pebbleBatch).Commit(0x18?, 0x0?)
F230508 22:22:00.549432 9359 3@pebble/db.go:811  [n5,s5,pebble] 1 !	github.com/cockroachdb/cockroach/pkg/storage/pebble_batch.go:549 +0x3e
F230508 22:22:00.549432 9359 3@pebble/db.go:811  [n5,s5,pebble] 1 !github.com/cockroachdb/cockroach/pkg/kv/kvserver/logstore.(*LogStore).storeEntriesAndCommitBatch(0xc00a9c6d30, {0x70f1a38, 0xc01083a900}, {0x0?, 0x0?, 0x0?}, {0x13, 0xffffffffffffffff, 0x2, 0x0, ...}, ...)
F230508 22:22:00.549432 9359 3@pebble/db.go:811  [n5,s5,pebble] 1 !	github.com/cockroachdb/cockroach/pkg/kv/kvserver/logstore/logstore.go:266 +0xae7
F230508 22:22:00.549432 9359 3@pebble/db.go:811  [n5,s5,pebble] 1 !github.com/cockroachdb/cockroach/pkg/kv/kvserver/logstore.(*LogStore).StoreEntries(0xc00a9c6d30, {0x70f1a38, 0xc01083a900}, {0xc001a64bb8?, 0x7f7bbc11a540?, 0x90?}, {0x13, 0xffffffffffffffff, 0x2, 0x0, ...}, ...)
F230508 22:22:00.549432 9359 3@pebble/db.go:811  [n5,s5,pebble] 1 !	github.com/cockroachdb/cockroach/pkg/kv/kvserver/logstore/logstore.go:139 +0x110
F230508 22:22:00.549432 9359 3@pebble/db.go:811  [n5,s5,pebble] 1 !github.com/cockroachdb/cockroach/pkg/kv/kvserver.(*Replica).handleRaftReadyRaftMuLocked(_, {_, _}, {{0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...}, ...})
F230508 22:22:00.549432 9359 3@pebble/db.go:811  [n5,s5,pebble] 1 !	github.com/cockroachdb/cockroach/pkg/kv/kvserver/pkg/kv/kvserver/replica_raft.go:972 +0x1137
F230508 22:22:00.549432 9359 3@pebble/db.go:811  [n5,s5,pebble] 1 !github.com/cockroachdb/cockroach/pkg/kv/kvserver.(*Replica).handleRaftReady(_, {_, _}, {{0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...}, ...})
F230508 22:22:00.549432 9359 3@pebble/db.go:811  [n5,s5,pebble] 1 !	github.com/cockroachdb/cockroach/pkg/kv/kvserver/pkg/kv/kvserver/replica_raft.go:718 +0x19b
F230508 22:22:00.549432 9359 3@pebble/db.go:811  [n5,s5,pebble] 1 !github.com/cockroachdb/cockroach/pkg/kv/kvserver.(*Store).processReady(0xc005d06a80, 0x70f1a38?)
F230508 22:22:00.549432 9359 3@pebble/db.go:811  [n5,s5,pebble] 1 !	github.com/cockroachdb/cockroach/pkg/kv/kvserver/pkg/kv/kvserver/store_raft.go:646 +0x145
F230508 22:22:00.549432 9359 3@pebble/db.go:811  [n5,s5,pebble] 1 !github.com/cockroachdb/cockroach/pkg/kv/kvserver.(*raftSchedulerShard).worker(0xc0028e1200, {0x70f1a38, 0xc00ab64960}, {0x70d61f0, 0xc005d06a80}, 0xc00a3b0000)
F230508 22:22:00.549432 9359 3@pebble/db.go:811  [n5,s5,pebble] 1 !	github.com/cockroachdb/cockroach/pkg/kv/kvserver/pkg/kv/kvserver/scheduler.go:392 +0x1f2
F230508 22:22:00.549432 9359 3@pebble/db.go:811  [n5,s5,pebble] 1 !github.com/cockroachdb/cockroach/pkg/kv/kvserver.(*raftScheduler).Start.func2({0x70f1a38?, 0xc00ab64960?})
F230508 22:22:00.549432 9359 3@pebble/db.go:811  [n5,s5,pebble] 1 !	github.com/cockroachdb/cockroach/pkg/kv/kvserver/pkg/kv/kvserver/scheduler.go:299 +0x45
F230508 22:22:00.549432 9359 3@pebble/db.go:811  [n5,s5,pebble] 1 !github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunAsyncTaskEx.func2()
```

**Comment by jbowens** [comment]
Linking to cockroachdb/cockroach#102945.
