### ISSUE TITLE
metamorphic: recent metamorphic runs appear to deadlock

### ISSUE THREAD

**Issue by jbowens** [cockroachdb/pebble#2597]
All recent nightlies of the metamorphic tests going back to ~April 27th seem to stall for hours.

Possibly related to https://github.com/cockroachdb/pebble/commit/497c8cc0f87e24902ebd00345c572b6ffebf51b4.

**Comment by itsbilal** [comment]
This is your classic deadlock. `maybeScheduleDelayedFlush` is trying to grab the commit mutex:

```
        goroutine 955 [semacquire, 4 minutes]:
        runtime.gopark(0x1015ec100?, 0x1009d0124?, 0x60?, 0x9e?, 0x14000302648?)
                /opt/homebrew/Cellar/go/1.19.2/libexec/src/runtime/proc.go:363 +0xe4 fp=0x1400030
25f0 sp=0x140003025d0 pc=0x1009b2ef4
        runtime.goparkunlock(...)
                /opt/homebrew/Cellar/go/1.19.2/libexec/src/runtime/proc.go:369
        runtime.semacquire1(0x140001bc93c, 0xa0?, 0x3, 0x1)
                /opt/homebrew/Cellar/go/1.19.2/libexec/src/runtime/sema.go:150 +0x20c fp=0x140003
02650 sp=0x140003025f0 pc=0x1009c46fc
        sync.runtime_SemacquireMutex(0x140000162e8?, 0x1?, 0x140003026b8?)
                /opt/homebrew/Cellar/go/1.19.2/libexec/src/runtime/sema.go:77 +0x24 fp=0x14000302
680 sp=0x14000302650 pc=0x1009dfcd4
        sync.(*Mutex).lockSlow(0x140001bc938)
                /opt/homebrew/Cellar/go/1.19.2/libexec/src/sync/mutex.go:171 +0x178 fp=0x14000302
6d0 sp=0x14000302680 pc=0x1009ecec8
        sync.(*Mutex).Lock(...)
                /opt/homebrew/Cellar/go/1.19.2/libexec/src/sync/mutex.go:90
        github.com/cockroachdb/pebble.(*DB).maybeScheduleDelayedFlush.func1()
                /Users/bilal/go/src/github.com/cockroachdb/pebble/compaction.go:1789 +0x130 fp=0x
140003027d0 sp=0x140003026d0 pc=0x100e10980
        runtime.goexit()
                /opt/homebrew/Cellar/go/1.19.2/libexec/src/runtime/asm_arm64.s:1172 +0x4 fp=0x140
003027d0 sp=0x140003027d0 pc=0x1009e44c4
        created by github.com/cockroachdb/pebble.(*DB).maybeScheduleDelayedFlush
                /Users/bilal/go/src/github.com/cockroachdb/pebble/compaction.go:1779 +0x1b4
```

while an ingestion is waiting on the `compact` cond lock (which drops the db mutex) while holding the commit mutex:


```
        goroutine 41 [sync.Cond.Wait, 4 minutes]:
        runtime.gopark(0x9d8f61f3?, 0x1400021e000?, 0x58?, 0x76?, 0x1009e11e0?)
                /opt/homebrew/Cellar/go/1.19.2/libexec/src/runtime/proc.go:363 +0xe4 fp=0x1400014
b610 sp=0x1400014b5f0 pc=0x1009b2ef4
        runtime.goparkunlock(...)
                /opt/homebrew/Cellar/go/1.19.2/libexec/src/runtime/proc.go:369
        sync.runtime_notifyListWait(0x14000426760, 0x2)
                /opt/homebrew/Cellar/go/1.19.2/libexec/src/runtime/sema.go:517 +0x16c fp=0x140001
4b660 sp=0x1400014b610 pc=0x1009dff0c
        sync.(*Cond).Wait(0x14000426750)
                /opt/homebrew/Cellar/go/1.19.2/libexec/src/sync/cond.go:70 +0xd0 fp=0x1400014b6a0
 sp=0x1400014b660 pc=0x1009eb060
        github.com/cockroachdb/pebble.(*DB).makeRoomForWrite(0x14000426500, 0x0)
                /Users/bilal/go/src/github.com/cockroachdb/pebble/db.go:2139 +0x168 fp=0x1400014b
790 sp=0x1400014b6a0 pc=0x100e31308
        github.com/cockroachdb/pebble.(*DB).ingest.func1(0x140001bb900?)
                /Users/bilal/go/src/github.com/cockroachdb/pebble/ingest.go:918 +0x404 fp=0x14000
14b8d0 sp=0x1400014b790 pc=0x100e459d4
        github.com/cockroachdb/pebble.(*commitPipeline).AllocateSeqNum(0x140001bb900, 0x1, 0x1400
0887bd8, 0x1400014bb78)
                /Users/bilal/go/src/github.com/cockroachdb/pebble/commit.go:409 +0x2bc fp=0x14000
14b940 sp=0x1400014b8d0 pc=0x100e072ec
        github.com/cockroachdb/pebble.(*DB).ingest(0x14000426500, {0x14000250f60, 0x2, 0x2}, 0x10
11c4cb0)
                /Users/bilal/go/src/github.com/cockroachdb/pebble/ingest.go:973 +0x32c fp=0x14000
14bc40 sp=0x1400014b940 pc=0x100e44cfc
        github.com/cockroachdb/pebble.(*DB).Ingest(0x14000887cc8?, {0x14000250f60?, 0x1015d3dc0?,
 0x1010dea80?})
                /Users/bilal/go/src/github.com/cockroachdb/pebble/ingest.go:657 +0x94 fp=0x140001
4bc90 sp=0x1400014bc40 pc=0x100e43f24
        github.com/cockroachdb/pebble/metamorphic.(*ingestOp).run.func1()
                /Users/bilal/go/src/github.com/cockroachdb/pebble/metamorphic/ops.go:480 +0x30 fp
=0x1400014bcc0 sp=0x1400014bc90 pc=0x100ed7d50
        github.com/cockroachdb/pebble/metamorphic.withRetries(0x1400014be50)
                /Users/bilal/go/src/github.com/cockroachdb/pebble/metamorphic/retryable.go:21 +0x
30 fp=0x1400014bd00 sp=0x1400014bcc0 pc=0x100ee30f0
        github.com/cockroachdb/pebble/metamorphic.(*ingestOp).run(0x140002826d8, 0x1400018c0e0, {
0x1400041d580?, 0x0?})
                /Users/bilal/go/src/github.com/cockroachdb/pebble/metamorphic/ops.go:479 +0x668 f
p=0x1400014be80 sp=0x1400014bd00 pc=0x100ed7c48
        github.com/cockroachdb/pebble/metamorphic.RunOnce.func1()
                /Users/bilal/go/src/github.com/cockroachdb/pebble/metamorphic/meta.go:498 +0x160
fp=0x1400014bf60 sp=0x1400014be80 pc=0x100ed4220
        golang.org/x/sync/errgroup.(*Group).Go.func1()
                /Users/bilal/go/pkg/mod/golang.org/x/sync@v0.0.0-20220722155255-886fb9371eb4/errg
roup/errgroup.go:75 +0x5c fp=0x1400014bfd0 sp=0x1400014bf60 pc=0x100ec275c
        runtime.goexit()
                /opt/homebrew/Cellar/go/1.19.2/libexec/src/runtime/asm_arm64.s:1172 +0x4 fp=0x140
0014bfd0 sp=0x1400014bfd0 pc=0x1009e44c4
        created by golang.org/x/sync/errgroup.(*Group).Go
                /Users/bilal/go/pkg/mod/golang.org/x/sync@v0.0.0-20220722155255-886fb9371eb4/errg
roup/errgroup.go:72 +0xa4
```

**Comment by itsbilal** [comment]
For reference, this is very easy to repro with seed `1686164945624607000`.
