### ISSUE TITLE
metamorphic: test failure in batchSort with nil pointer

### ISSUE THREAD

**Issue by itsbilal** [cockroachdb/pebble#2671]
See [failure](https://teamcity.cockroachdb.com/viewLog.html?buildId=10643967&buildTypeId=Cockroach_Nightlies_Pebble_Metamorphic)

```
  ===== SEED =====
        1687508258078783067
        ===== ERR =====
        exit status 2
        ===== OUT =====
        panic: runtime error: invalid memory address or nil pointer dereference
        [signal SIGSEGV: segmentation violation code=0x1 addr=0x48 pc=0x949c45]
        
        goroutine 67 [running]:
        github.com/cockroachdb/pebble.batchSort({0xcff500?, 0xc000540000?})
        	github.com/cockroachdb/pebble/external/com_github_cockroachdb_pebble/batch.go:2211 +0x205
        github.com/cockroachdb/pebble/metamorphic.(*ingestOp).build(0xc0002e9d48?, 0xc0001862a0, {0xc00003eb10?, 0x1?}, 0x0?, 0xc0002e9e88?)
        	github.com/cockroachdb/pebble/metamorphic/external/com_github_cockroachdb_pebble/metamorphic/ops.go:492 +0x1ea
        github.com/cockroachdb/pebble/metamorphic.(*ingestOp).run(0xc000256498, 0xc0001862a0, {0xc000408520?, 0x0?})
        	github.com/cockroachdb/pebble/metamorphic/external/com_github_cockroachdb_pebble/metamorphic/ops.go:466 +0x565
        github.com/cockroachdb/pebble/metamorphic.RunOnce.func1()
        	github.com/cockroachdb/pebble/metamorphic/external/com_github_cockroachdb_pebble/metamorphic/meta.go:498 +0x179
        golang.org/x/sync/errgroup.(*Group).Go.func1()
        	golang.org/x/sync/errgroup/external/org_golang_x_sync/errgroup/errgroup.go:75 +0x64
        created by golang.org/x/sync/errgroup.(*Group).Go
        	golang.org/x/sync/errgroup/external/org_golang_x_sync/errgroup/errgroup.go:72 +0xa5
```

**Comment by itsbilal** [comment]
Possibly caused by #2655

**Comment by bananabrick** [comment]
```
        batch19 = db.NewIndexedBatch()
        batch18.Apply(batch17)
        batch17.Close()
        db.SingleDelete("uzto@5", true /* maybeReplaceDelete */)
        batch19.Delete("vidzasqfq@3")
        db.DeleteRange("dsbjht@4", "zkvcc@6")
        db.Delete("fjuttusqr@3")
        db.Set("dgfhnfnl@1", "nfnpmzoi")
        db.Delete("xnkmu@7")
        db.Ingest(batch19)
```

That's the broken sequence of operations.

**Comment by bananabrick** [comment]
@RahulAggarwal1016 If you look at the `applyOp.run` in `ops.go`, it's calling `batch.Close`. So, we put `batch17` into the batch pool. The batch gets used by `batch19`. But the `batch17.Close` unsets `batch19.db`.

We have a duplicate close call, because apply was already closing the batch.

I actually like the approach where we just call `batch.Close` within the `applyOp.run`.

**Comment by bananabrick** [comment]
One way to fix this is to get rid of this call to `batch.Close` https://github.com/cockroachdb/pebble/pull/2655/files#diff-48d6e2867e1cfd3825764838e732072d3c324829fa227c9c58ad246770781566R87.
