### ISSUE TITLE
System crash

### ISSUE THREAD

**Issue by rjl493456442** [cockroachdb/pebble#2820]
We (go-ethereum) are using pebble as the backend storage engine, the version is `v0.0.0-20230209160836-829675f94811`.
We met this weird panic in arena-skiplist

```
Aug 12 19:45:55 bench06.ethdevops.io geth unexpected fault address 0xfffffffffffffea6
Aug 12 19:45:55 bench06.ethdevops.io geth fatal error: fault
Aug 12 19:45:55 bench06.ethdevops.io geth [signal SIGSEGV: segmentation violation code=0x1 addr=0xfffffffffffffea6 pc=0xae29bd]
Aug 12 19:45:55 bench06.ethdevops.io geth goroutine 66957864 [running]:
Aug 12 19:45:55 bench06.ethdevops.io geth runtime.throw({0x1acb143?, 0x4da57e2b46bd0a0?})
Aug 12 19:45:55 bench06.ethdevops.io geth 	runtime/panic.go:1047 +0x5d fp=0xc024ab1f10 sp=0xc024ab1ee0 pc=0x43a45d
Aug 12 19:45:55 bench06.ethdevops.io geth runtime.sigpanic()
Aug 12 19:45:55 bench06.ethdevops.io geth 	runtime/signal_unix.go:855 +0x28a fp=0xc024ab1f70 sp=0xc024ab1f10 pc=0x45176a
Aug 12 19:45:55 bench06.ethdevops.io geth github.com/cockroachdb/pebble/internal/arenaskl.(*Skiplist).getNext(...)
Aug 12 19:45:55 bench06.ethdevops.io geth 	github.com/cockroachdb/pebble@v0.0.0-20230209160836-829675f94811/internal/arenaskl/skl.go:472
Aug 12 19:45:55 bench06.ethdevops.io geth github.com/cockroachdb/pebble/internal/arenaskl.(*Skiplist).findSpliceForLevel(0xc0ef8de030, {{0xc0837838c0?, 0x0?, 0xc024ab2090?}, 0xb4abae?}, 0x0, 0x0?)
Aug 12 19:45:55 bench06.ethdevops.io geth 	github.com/cockroachdb/pebble@v0.0.0-20230209160836-829675f94811/internal/arenaskl/skl.go:407 +0x7d fp=0xc024ab2000 sp=0xc024ab1f70 pc=0xae29bd
Aug 12 19:45:55 bench06.ethdevops.io geth github.com/cockroachdb/pebble/internal/arenaskl.(*Iterator).seekForBaseSplice(0xc01c3ca0c0, {0xc0837838c0, 0x21, 0x30})
Aug 12 19:45:55 bench06.ethdevops.io geth 	github.com/cockroachdb/pebble@v0.0.0-20230209160836-829675f94811/internal/arenaskl/iterator.go:262 +0x74 fp=0xc024ab2050 sp=0xc024ab2000 pc=0xae14f4
Aug 12 19:45:55 bench06.ethdevops.io geth github.com/cockroachdb/pebble/internal/arenaskl.(*Iterator).SeekGE(0xc01c3ca0c0, {0xc0837838c0?, 0xa492a8ae89518848?, 0xc05b07a780?}, 0x15?)
Aug 12 19:45:55 bench06.ethdevops.io geth 	github.com/cockroachdb/pebble@v0.0.0-20230209160836-829675f94811/internal/arenaskl/iterator.go:105 +0x99 fp=0xc024ab20a0 sp=0xc024ab2050 pc=0xae0219
Aug 12 19:45:55 bench06.ethdevops.io geth github.com/cockroachdb/pebble.(*getIter).Next(0xc02d2de060)
Aug 12 19:45:55 bench06.ethdevops.io geth 	github.com/cockroachdb/pebble@v0.0.0-20230209160836-829675f94811/get_iter.go:151 +0xbef fp=0xc024ab2908 sp=0xc024ab20a0 pc=0xb2dd4f
Aug 12 19:45:55 bench06.ethdevops.io geth github.com/cockroachdb/pebble.(*getIter).First(0x0?)
Aug 12 19:45:55 bench06.ethdevops.io geth 	github.com/cockroachdb/pebble@v0.0.0-20230209160836-829675f94811/get_iter.go:65 +0x19 fp=0xc024ab2920 sp=0xc024ab2908 pc=0xb2d0f9
Aug 12 19:45:55 bench06.ethdevops.io geth github.com/cockroachdb/pebble.(*Iterator).iterFirstWithinBounds(0xc02d2ddb00)
Aug 12 19:45:55 bench06.ethdevops.io geth 	github.com/cockroachdb/pebble@v0.0.0-20230209160836-829675f94811/iterator.go:1945 +0xe2 fp=0xc024ab2958 sp=0xc024ab2920 pc=0xb3b822
Aug 12 19:45:55 bench06.ethdevops.io geth github.com/cockroachdb/pebble.(*Iterator).First(0xc02d2ddb00)
Aug 12 19:45:55 bench06.ethdevops.io geth 	github.com/cockroachdb/pebble@v0.0.0-20230209160836-829675f94811/iterator.go:1544 +0xed fp=0xc024ab2988 sp=0xc024ab2958 pc=0xb3a66d
Aug 12 19:45:55 bench06.ethdevops.io geth github.com/cockroachdb/pebble.(*DB).getInternal(0xc0004eca00, {0xc0837838c0, 0x21, 0x30}, 0x0, 0x0)
Aug 12 19:45:55 bench06.ethdevops.io geth 	github.com/cockroachdb/pebble@v0.0.0-20230209160836-829675f94811/db.go:573 +0x399 fp=0xc024ab3268 sp=0xc024ab2988 pc=0xb183b9
Aug 12 19:45:55 bench06.ethdevops.io geth github.com/cockroachdb/pebble.(*DB).Get(...)
Aug 12 19:45:55 bench06.ethdevops.io geth 	github.com/cockroachdb/pebble@v0.0.0-20230209160836-829675f94811/db.go:501
Aug 12 19:45:55 bench06.ethdevops.io geth github.com/ethereum/go-ethereum/ethdb/pebble.(*Database).Get(0x30?, {0xc0837838c0?, 0xc0837838c0?, 0x0?})
```

The version we used is pretty old, i am not sure if this is still relevant, the corresponding code is

```go
func (s *Skiplist) getNext(nd *node, h int) *node {
	offset := atomic.LoadUint32(&nd.tower[h].nextOffset)
	return (*node)(s.arena.getPointer(offset))
}
```

**Comment by RaduBerinde** [comment]
@rjl493456442 do you have a ballpark idea how much memory Pebble was using when this happened? I'm wondering if Pebble is trying to have an arena larger than 4GB.

**Comment by RaduBerinde** [comment]
Looks like it happens on the `offset := atomic.LoadUint32(&nd.tower[h].nextOffset)` line and the offending address (`addr=0xfffffffffffffea6`) is 345 bytes short of the end of the address space. Not quite sure how that can happen.

**Comment by itsbilal** [comment]
@rjl493456442 Also, if we could get the pebble `Options` that this instance of Pebble was initialized with, that'd also help in narrowing this down. Might also help to know what OS and architecture this was. Thanks!

**Comment by rjl493456442** [comment]
OS & Arch: `Debian 5.10.158-2 (2022-12-13) x86_64 GNU/Linux`


The option we use is:

```go
opt := &pebble.Options{
		// Pebble has a single combined cache area and the write
		// buffers are taken from this too. Assign all available
		// memory allowance for cache.
		Cache:        pebble.NewCache(int64(2 * 1024 * 1024 * 1024)),
		MaxOpenFiles: <a half of system fd limit>,

		// The size of memory table(as well as the write buffer).
		// Note, there may have more than two memory tables in the system.
		MemTableSize: 1024 * 1024 * 1024,

		// MemTableStopWritesThreshold places a hard limit on the size
		// of the existent MemTables(including the frozen one).
		// Note, this must be the number of tables not the size of all memtables
		// according to https://github.com/cockroachdb/pebble/blob/master/options.go#L738-L742
		// and to https://github.com/cockroachdb/pebble/blob/master/db.go#L1892-L1903.
		MemTableStopWritesThreshold: 1024 * 1024 * 1024,

		// The default compaction concurrency(1 thread),
		// Here use all available CPUs for faster compaction.
		MaxConcurrentCompactions: func() int { return runtime.NumCPU() },

		// Per-level options. Options for at least one level must be specified. The
		// options for the last level are used for all subsequent levels.
		Levels: []pebble.LevelOptions{
			{TargetFileSize: 2 * 1024 * 1024, FilterPolicy: bloom.FilterPolicy(10)},
			{TargetFileSize: 2 * 1024 * 1024, FilterPolicy: bloom.FilterPolicy(10)},
			{TargetFileSize: 2 * 1024 * 1024, FilterPolicy: bloom.FilterPolicy(10)},
			{TargetFileSize: 2 * 1024 * 1024, FilterPolicy: bloom.FilterPolicy(10)},
			{TargetFileSize: 2 * 1024 * 1024, FilterPolicy: bloom.FilterPolicy(10)},
			{TargetFileSize: 2 * 1024 * 1024, FilterPolicy: bloom.FilterPolicy(10)},
			{TargetFileSize: 2 * 1024 * 1024, FilterPolicy: bloom.FilterPolicy(10)},
		},
		ReadOnly: readonly,
		EventListener: &pebble.EventListener{
			CompactionBegin: db.onCompactionBegin,
			CompactionEnd:   db.onCompactionEnd,
			WriteStallBegin: db.onWriteStallBegin,
			WriteStallEnd:   db.onWriteStallEnd,
		},
	}
	// Disable seek compaction explicitly. Check https://github.com/ethereum/go-ethereum/pull/20130
	// for more details.
	opt.Experimental.ReadSamplingMultiplier = -1
```

**Comment by rjl493456442** [comment]
We have been using pebble for a few months, it's the first time to see this panic though.

**Comment by RaduBerinde** [comment]
Not related to the crash but `MemTableStopWritesThreshold` should be a small number - it is the max number of mem tables (which you have configured at MemTableSize=1GB each). The default is 2. CockroachDB uses 4 with MemTableSize=64MB.

**Comment by rjl493456442** [comment]
Sorry it's 2. I interpret it incorrectly.

**Comment by RaduBerinde** [comment]
@rjl493456442 There is not much to go on from our end.. Are you able to reproduce this failure? Also, can you try a newer pebble version?
