### ISSUE TITLE
panic: pebble: flush-to key (NRK4VxF) < flushed key (NijFwKPxZE)

### ISSUE THREAD

**Issue by petermattis** [cockroachdb/pebble#317]
Reproducible when running the metamorphic test with the standard options `LevelOptions.TargetFileSize = 1`:

```
panic: pebble: flush-to key (NRK4VxF) < flushed key (NijFwKPxZE)

goroutine 10 [running]:
github.com/cockroachdb/pebble/internal/rangedel.(*Fragmenter).FlushTo(0xc00000c2d0, 0xc0001d3ce0, 0x7, 0x8)
	/Users/pmattis/Development/go/src/github.com/cockroachdb/pebble/internal/rangedel/fragmenter.go:291 +0x79e
github.com/cockroachdb/pebble.(*compactionIter).Tombstones(0xc00000c1e0, 0xc0001d3ce0, 0x7, 0x8, 0x7, 0xc0001d3ce0, 0x0)
	/Users/pmattis/Development/go/src/github.com/cockroachdb/pebble/compaction_iter.go:485 +0x11f
github.com/cockroachdb/pebble.(*DB).runCompaction.func4(0xc0001d3580, 0x7, 0x10, 0x2, 0x8, 0xc0001d3710)
	/Users/pmattis/Development/go/src/github.com/cockroachdb/pebble/compaction.go:1038 +0xff
github.com/cockroachdb/pebble.(*DB).runCompaction(0xc0000bea00, 0x19, 0xc000244380, 0x1480d20, 0xc0000903c0, 0x5, 0x8, 0xc000104000, 0x15, 0x0, ...)
	/Users/pmattis/Development/go/src/github.com/cockroachdb/pebble/compaction.go:1116 +0xcc0
github.com/cockroachdb/pebble.(*DB).compact1(0xc0000bea00, 0x0, 0x0)
	/Users/pmattis/Development/go/src/github.com/cockroachdb/pebble/compaction.go:875 +0x519
github.com/cockroachdb/pebble.(*DB).compact(0xc0000bea00)
	/Users/pmattis/Development/go/src/github.com/cockroachdb/pebble/compaction.go:824 +0x71
created by github.com/cockroachdb/pebble.(*DB).maybeScheduleCompaction
	/Users/pmattis/Development/go/src/github.com/cockroachdb/pebble/compaction.go:817 +0xab
```

**Comment by petermattis** [comment]
`compactionIter` is adding range tombstones too early to `rangedel.Fragmenter`. Some instrumentation shows the following:

```
compactionIter.iterNext: NRK4VxF#568,2
compactionIter.iterNext: NijFwKPxZE#571,15
Fragmenter.truncateAndFlush: NijFwKPxZE
Fragmenter.FlushTo: NRK4VxF
```

So `compactionIter` saw `NRK4VxF`, and then took a look at the next record and found `NijFwKPxZE`. That record was a range tombstone so it added it to the fragmenter. That record also had a different user-key than `NRK4VxF`, so it returned `NRK4VxF` as the key to output. This key happened to exceed the target file size threshold, so we flushed all of the tombstones up to `NRK4VxF` via a call to `Fragmenter.FlushTo`. 

We could relax the panic, but I think it is sound. Consider what happens if we had the records `c#10, [c-q)#9, [q-z)#11`. `compactionIter` would see `c#10`, then look ahead and find `[c-q)#9`, add that range tombstone to the fragmenter, then look ahead again and find `[q-z)#11`. Adding `[q-z)#11` to the fragmenter would trigger `[c-q)#9` to be emitted as a fragment. And then the key `c#10` could trigger a switch to the next sstable which means we didn't want to emit `[c-q)#9`.

**Comment by petermattis** [comment]
Turns out I broke this with a simplification refactor a little while back. The fix is straightforward.
