### ISSUE TITLE
db: TestIteratorErrors failed [iterator is valid with non-nil Error]

### ISSUE THREAD

**Issue by jbowens** [cockroachdb/pebble#3234]
https://github.com/cockroachdb/pebble/actions/runs/7568342774/job/20609357007
```
=== RUN   TestIteratorErrors
    external_test.go:31: Using seed 1705572529975016370
```

```
--- FAIL: TestIteratorErrors (1.79s)
panic: pebble: iterator is valid with non-nil Error [recovered]
	panic: pebble: iterator is valid with non-nil Error

goroutine 121985 [running]:
testing.tRunner.func1.2({0xd72be0, 0xc00136b940})
	/opt/hostedtoolcache/go/1.21.5/x64/src/testing/testing.go:1545 +0x238
testing.tRunner.func1()
	/opt/hostedtoolcache/go/1.21.5/x64/src/testing/testing.go:1548 +0x397
panic({0xd72be0?, 0xc00136b940?})
	/opt/hostedtoolcache/go/1.21.5/x64/src/runtime/panic.go:914 +0x21f
github.com/cockroachdb/pebble.(*Iterator).Valid(0xc001e22800?)
	/home/runner/work/pebble/pebble/iterator.go:2241 +0x87
github.com/cockroachdb/pebble/metamorphic.(*retryableIter).withRetry(0xc0034426c0, 0xc000ca1960)
	/home/runner/work/pebble/pebble/metamorphic/retryable.go:57 +0x66
github.com/cockroachdb/pebble/metamorphic.(*retryableIter).SeekGE(0xc003529820?, {0xc002071e37?, 0xc002720090?, 0xe09e58?})
	/home/runner/work/pebble/pebble/metamorphic/retryable.go:147 +0x5e
github.com/cockroachdb/pebble/metamorphic.(*iterSeekGEOp).run(0xc004390c40, 0x4131c5?, {0xc003529820?, 0xd3f980?, 0xc002720100?})
	/home/runner/work/pebble/pebble/metamorphic/ops.go:1356 +0xd1
github.com/cockroachdb/pebble/metamorphic.(*Test).step(0xc000d76960, 0xc00022b340?, 0x2c?)
	/home/runner/work/pebble/pebble/metamorphic/test.go:352 +0x48
github.com/cockroachdb/pebble/metamorphic.(*Test).Step(0xc000d76960)
	/home/runner/work/pebble/pebble/metamorphic/test.go:341 +0x75
github.com/cockroachdb/pebble_test.TestIteratorErrors(0xc00057b380)
	/home/runner/work/pebble/pebble/external_test.go:86 +0x898
testing.tRunner(0xc00057b380, 0xe5c3d8)
	/opt/hostedtoolcache/go/1.21.5/x64/src/testing/testing.go:1595 +0xff
created by testing.(*T).Run in goroutine 1
	/opt/hostedtoolcache/go/1.21.5/x64/src/testing/testing.go:1648 +0x3ad
```

**Comment by jbowens** [comment]
Ran it with a change to print the verbose error on failure (to capture the stack of when the error was injected):

```
panic: pebble: backing file 003036 error: injected error
(1) attached stack trace
  -- stack trace:
  | github.com/cockroachdb/pebble.(*tableCacheValue).load
  | 	/Users/jackson/go/src/github.com/cockroachdb/pebble/table_cache.go:1131
  | github.com/cockroachdb/pebble.(*tableCacheShard).findNodeInternal.func2
  | 	/Users/jackson/go/src/github.com/cockroachdb/pebble/table_cache.go:883
  | runtime/pprof.Do
  | 	/usr/local/go/src/runtime/pprof/runtime.go:51
  | github.com/cockroachdb/pebble.(*tableCacheShard).findNodeInternal
  | 	/Users/jackson/go/src/github.com/cockroachdb/pebble/table_cache.go:882
  | github.com/cockroachdb/pebble.(*tableCacheShard).findNode
  | 	/Users/jackson/go/src/github.com/cockroachdb/pebble/table_cache.go:778
  | github.com/cockroachdb/pebble.(*tableCacheShard).newRangeKeyIter
  | 	/Users/jackson/go/src/github.com/cockroachdb/pebble/table_cache.go:596
  | github.com/cockroachdb/pebble.(*tableCacheContainer).newRangeKeyIter
  | 	/Users/jackson/go/src/github.com/cockroachdb/pebble/table_cache.go:150
  | github.com/cockroachdb/pebble/internal/keyspan.(*LevelIter).loadFile
  | 	/Users/jackson/go/src/github.com/cockroachdb/pebble/internal/keyspan/level_iter.go:183
  | github.com/cockroachdb/pebble/internal/keyspan.(*LevelIter).skipEmptyFileForward
  | 	/Users/jackson/go/src/github.com/cockroachdb/pebble/internal/keyspan/level_iter.go:415
  | github.com/cockroachdb/pebble/internal/keyspan.(*LevelIter).Next
  | 	/Users/jackson/go/src/github.com/cockroachdb/pebble/internal/keyspan/level_iter.go:345
  | github.com/cockroachdb/pebble/internal/keyspan.(*mergingIterLevel).next
  | 	/Users/jackson/go/src/github.com/cockroachdb/pebble/internal/keyspan/merging_iter.go:251
  | github.com/cockroachdb/pebble/internal/keyspan.(*MergingIter).nextEntry
  | 	/Users/jackson/go/src/github.com/cockroachdb/pebble/internal/keyspan/merging_iter.go:1041
  | github.com/cockroachdb/pebble/internal/keyspan.(*MergingIter).findNextFragmentSet
  | 	/Users/jackson/go/src/github.com/cockroachdb/pebble/internal/keyspan/merging_iter.go:865
  | github.com/cockroachdb/pebble/internal/keyspan.(*MergingIter).Next
  | 	/Users/jackson/go/src/github.com/cockroachdb/pebble/internal/keyspan/merging_iter.go:640
  | github.com/cockroachdb/pebble/internal/keyspan.(*BoundedIter).Next
  | 	/Users/jackson/go/src/github.com/cockroachdb/pebble/internal/keyspan/bounded.go:159
  | github.com/cockroachdb/pebble/internal/keyspan.(*DefragmentingIter).defragmentForward
  | 	/Users/jackson/go/src/github.com/cockroachdb/pebble/internal/keyspan/defragment.go:441
  | github.com/cockroachdb/pebble/internal/keyspan.(*DefragmentingIter).Next
  | 	/Users/jackson/go/src/github.com/cockroachdb/pebble/internal/keyspan/defragment.go:357
  | github.com/cockroachdb/pebble/internal/keyspan.(*assertIter).Next
  | 	/Users/jackson/go/src/github.com/cockroachdb/pebble/internal/keyspan/assert_iter.go:147
  | github.com/cockroachdb/pebble/internal/keyspan.(*InterleavingIter).nextPos
  | 	/Users/jackson/go/src/github.com/cockroachdb/pebble/internal/keyspan/interleaving_iter.go:681
  | github.com/cockroachdb/pebble/internal/keyspan.(*InterleavingIter).yieldPosition
  | 	/Users/jackson/go/src/github.com/cockroachdb/pebble/internal/keyspan/interleaving_iter.go:807
  | github.com/cockroachdb/pebble/internal/keyspan.(*InterleavingIter).Next
  | 	/Users/jackson/go/src/github.com/cockroachdb/pebble/internal/keyspan/interleaving_iter.go:478
  | github.com/cockroachdb/pebble.(*Iterator).nextPointCurrentUserKey
  | 	/Users/jackson/go/src/github.com/cockroachdb/pebble/iterator.go:654
  | github.com/cockroachdb/pebble.(*Iterator).findNextEntry
  | 	/Users/jackson/go/src/github.com/cockroachdb/pebble/iterator.go:587
  | github.com/cockroachdb/pebble.(*Iterator).First
  | 	/Users/jackson/go/src/github.com/cockroachdb/pebble/iterator.go:1623
  | github.com/cockroachdb/pebble/metamorphic.(*retryableIter).First.func1
  | 	/Users/jackson/go/src/github.com/cockroachdb/pebble/metamorphic/retryable.go:73
  | github.com/cockroachdb/pebble/metamorphic.(*retryableIter).withRetry
  | 	/Users/jackson/go/src/github.com/cockroachdb/pebble/metamorphic/retryable.go:47
  | github.com/cockroachdb/pebble/metamorphic.(*retryableIter).First
  | 	/Users/jackson/go/src/github.com/cockroachdb/pebble/metamorphic/retryable.go:72
  | github.com/cockroachdb/pebble/metamorphic.(*iterFirstOp).run
  | 	/Users/jackson/go/src/github.com/cockroachdb/pebble/metamorphic/ops.go:1474
  | github.com/cockroachdb/pebble/metamorphic.(*Test).step
  | 	/Users/jackson/go/src/github.com/cockroachdb/pebble/metamorphic/test.go:352
  | github.com/cockroachdb/pebble/metamorphic.(*Test).Step
  | 	/Users/jackson/go/src/github.com/cockroachdb/pebble/metamorphic/test.go:341
  | github.com/cockroachdb/pebble_test.TestIteratorErrors
  | 	/Users/jackson/go/src/github.com/cockroachdb/pebble/external_test.go:85
Wraps: (2) pebble: backing file 003036 error
Wraps: (3) attached stack trace
  -- stack trace:
  | github.com/cockroachdb/pebble/vfs/errorfs.LabelledError.MaybeError
  | 	/Users/jackson/go/src/github.com/cockroachdb/pebble/vfs/errorfs/dsl.go:259
  | github.com/cockroachdb/pebble/vfs/errorfs.(*Counter).MaybeError
  | 	/Users/jackson/go/src/github.com/cockroachdb/pebble/vfs/errorfs/errorfs.go:213
  | github.com/cockroachdb/pebble/vfs/errorfs.(*Toggle).MaybeError
  | 	/Users/jackson/go/src/github.com/cockroachdb/pebble/vfs/errorfs/errorfs.go:257
  | github.com/cockroachdb/pebble/vfs/errorfs.(*errorFile).Stat
  | 	/Users/jackson/go/src/github.com/cockroachdb/pebble/vfs/errorfs/errorfs.go:505
  | github.com/cockroachdb/pebble/objstorage/objstorageprovider.newFileReadable
  | 	/Users/jackson/go/src/github.com/cockroachdb/pebble/objstorage/objstorageprovider/vfs_readable.go:37
  | github.com/cockroachdb/pebble/objstorage/objstorageprovider.(*provider).vfsOpenForReading
  | 	/Users/jackson/go/src/github.com/cockroachdb/pebble/objstorage/objstorageprovider/vfs.go:34
  | github.com/cockroachdb/pebble/objstorage/objstorageprovider.(*provider).OpenForReading
  | 	/Users/jackson/go/src/github.com/cockroachdb/pebble/objstorage/objstorageprovider/provider.go:226
  | github.com/cockroachdb/pebble.(*tableCacheValue).load
  | 	/Users/jackson/go/src/github.com/cockroachdb/pebble/table_cache.go:1123
  | github.com/cockroachdb/pebble.(*tableCacheShard).findNodeInternal.func2
  | 	/Users/jackson/go/src/github.com/cockroachdb/pebble/table_cache.go:883
  | runtime/pprof.Do
  | 	/usr/local/go/src/runtime/pprof/runtime.go:51
  | github.com/cockroachdb/pebble.(*tableCacheShard).findNodeInternal
  | 	/Users/jackson/go/src/github.com/cockroachdb/pebble/table_cache.go:882
  | github.com/cockroachdb/pebble.(*tableCacheShard).findNode
  | 	/Users/jackson/go/src/github.com/cockroachdb/pebble/table_cache.go:778
  | github.com/cockroachdb/pebble.(*tableCacheShard).newRangeKeyIter
  | 	/Users/jackson/go/src/github.com/cockroachdb/pebble/table_cache.go:596
  | github.com/cockroachdb/pebble.(*tableCacheContainer).newRangeKeyIter
  | 	/Users/jackson/go/src/github.com/cockroachdb/pebble/table_cache.go:150
  | github.com/cockroachdb/pebble/internal/keyspan.(*LevelIter).loadFile
  | 	/Users/jackson/go/src/github.com/cockroachdb/pebble/internal/keyspan/level_iter.go:183
  | github.com/cockroachdb/pebble/internal/keyspan.(*LevelIter).skipEmptyFileForward
  | 	/Users/jackson/go/src/github.com/cockroachdb/pebble/internal/keyspan/level_iter.go:415
  | github.com/cockroachdb/pebble/internal/keyspan.(*LevelIter).Next
  | 	/Users/jackson/go/src/github.com/cockroachdb/pebble/internal/keyspan/level_iter.go:345
  | github.com/cockroachdb/pebble/internal/keyspan.(*mergingIterLevel).next
  | 	/Users/jackson/go/src/github.com/cockroachdb/pebble/internal/keyspan/merging_iter.go:251
  | github.com/cockroachdb/pebble/internal/keyspan.(*MergingIter).nextEntry
  | 	/Users/jackson/go/src/github.com/cockroachdb/pebble/internal/keyspan/merging_iter.go:1041
  | github.com/cockroachdb/pebble/internal/keyspan.(*MergingIter).findNextFragmentSet
  | 	/Users/jackson/go/src/github.com/cockroachdb/pebble/internal/keyspan/merging_iter.go:865
  | github.com/cockroachdb/pebble/internal/keyspan.(*MergingIter).Next
  | 	/Users/jackson/go/src/github.com/cockroachdb/pebble/internal/keyspan/merging_iter.go:640
  | github.com/cockroachdb/pebble/internal/keyspan.(*BoundedIter).Next
  | 	/Users/jackson/go/src/github.com/cockroachdb/pebble/internal/keyspan/bounded.go:159
  | github.com/cockroachdb/pebble/internal/keyspan.(*DefragmentingIter).defragmentForward
  | 	/Users/jackson/go/src/github.com/cockroachdb/pebble/internal/keyspan/defragment.go:441
  | github.com/cockroachdb/pebble/internal/keyspan.(*DefragmentingIter).Next
  | 	/Users/jackson/go/src/github.com/cockroachdb/pebble/internal/keyspan/defragment.go:357
  | github.com/cockroachdb/pebble/internal/keyspan.(*assertIter).Next
  | 	/Users/jackson/go/src/github.com/cockroachdb/pebble/internal/keyspan/assert_iter.go:147
  | github.com/cockroachdb/pebble/internal/keyspan.(*InterleavingIter).nextPos
  | 	/Users/jackson/go/src/github.com/cockroachdb/pebble/internal/keyspan/interleaving_iter.go:681
  | github.com/cockroachdb/pebble/internal/keyspan.(*InterleavingIter).yieldPosition
  | 	/Users/jackson/go/src/github.com/cockroachdb/pebble/internal/keyspan/interleaving_iter.go:807
  | github.com/cockroachdb/pebble/internal/keyspan.(*InterleavingIter).Next
  | 	/Users/jackson/go/src/github.com/cockroachdb/pebble/internal/keyspan/interleaving_iter.go:478
  | github.com/cockroachdb/pebble.(*Iterator).nextPointCurrentUserKey
  | 	/Users/jackson/go/src/github.com/cockroachdb/pebble/iterator.go:654
  | github.com/cockroachdb/pebble.(*Iterator).findNextEntry
  | 	/Users/jackson/go/src/github.com/cockroachdb/pebble/iterator.go:587
  | github.com/cockroachdb/pebble.(*Iterator).First
  | 	/Users/jackson/go/src/github.com/cockroachdb/pebble/iterator.go:1623
  | github.com/cockroachdb/pebble/metamorphic.(*retryableIter).First.func1
  | 	/Users/jackson/go/src/github.com/cockroachdb/pebble/metamorphic/retryable.go:73
Wraps: (4) injected error
Error types: (1) *withstack.withStack (2) *errutil.withPrefix (3) *withstack.withStack (4) errorfs.LabelledError [recovered]
	panic: pebble: backing file 003036 error: injected error
(1) attached stack trace
  -- stack trace:
  | github.com/cockroachdb/pebble.(*tableCacheValue).load
  | 	/Users/jackson/go/src/github.com/cockroachdb/pebble/table_cache.go:1131
  | github.com/cockroachdb/pebble.(*tableCacheShard).findNodeInternal.func2
  | 	/Users/jackson/go/src/github.com/cockroachdb/pebble/table_cache.go:883
  | runtime/pprof.Do
  | 	/usr/local/go/src/runtime/pprof/runtime.go:51
  | github.com/cockroachdb/pebble.(*tableCacheShard).findNodeInternal
  | 	/Users/jackson/go/src/github.com/cockroachdb/pebble/table_cache.go:882
  | github.com/cockroachdb/pebble.(*tableCacheShard).findNode
  | 	/Users/jackson/go/src/github.com/cockroachdb/pebble/table_cache.go:778
  | github.com/cockroachdb/pebble.(*tableCacheShard).newRangeKeyIter
  | 	/Users/jackson/go/src/github.com/cockroachdb/pebble/table_cache.go:596
  | github.com/cockroachdb/pebble.(*tableCacheContainer).newRangeKeyIter
  | 	/Users/jackson/go/src/github.com/cockroachdb/pebble/table_cache.go:150
  | github.com/cockroachdb/pebble/internal/keyspan.(*LevelIter).loadFile
  | 	/Users/jackson/go/src/github.com/cockroachdb/pebble/internal/keyspan/level_iter.go:183
  | github.com/cockroachdb/pebble/internal/keyspan.(*LevelIter).skipEmptyFileForward
  | 	/Users/jackson/go/src/github.com/cockroachdb/pebble/internal/keyspan/level_iter.go:415
  | github.com/cockroachdb/pebble/internal/keyspan.(*LevelIter).Next
  | 	/Users/jackson/go/src/github.com/cockroachdb/pebble/internal/keyspan/level_iter.go:345
  | github.com/cockroachdb/pebble/internal/keyspan.(*mergingIterLevel).next
  | 	/Users/jackson/go/src/github.com/cockroachdb/pebble/internal/keyspan/merging_iter.go:251
  | github.com/cockroachdb/pebble/internal/keyspan.(*MergingIter).nextEntry
  | 	/Users/jackson/go/src/github.com/cockroachdb/pebble/internal/keyspan/merging_iter.go:1041
  | github.com/cockroachdb/pebble/internal/keyspan.(*MergingIter).findNextFragmentSet
  | 	/Users/jackson/go/src/github.com/cockroachdb/pebble/internal/keyspan/merging_iter.go:865
  | github.com/cockroachdb/pebble/internal/keyspan.(*MergingIter).Next
  | 	/Users/jackson/go/src/github.com/cockroachdb/pebble/internal/keyspan/merging_iter.go:640
  | github.com/cockroachdb/pebble/internal/keyspan.(*BoundedIter).Next
  | 	/Users/jackson/go/src/github.com/cockroachdb/pebble/internal/keyspan/bounded.go:159
  | github.com/cockroachdb/pebble/internal/keyspan.(*DefragmentingIter).defragmentForward
  | 	/Users/jackson/go/src/github.com/cockroachdb/pebble/internal/keyspan/defragment.go:441
  | github.com/cockroachdb/pebble/internal/keyspan.(*DefragmentingIter).Next
  | 	/Users/jackson/go/src/github.com/cockroachdb/pebble/internal/keyspan/defragment.go:357
  | github.com/cockroachdb/pebble/internal/keyspan.(*assertIter).Next
  | 	/Users/jackson/go/src/github.com/cockroachdb/pebble/internal/keyspan/assert_iter.go:147
  | github.com/cockroachdb/pebble/internal/keyspan.(*InterleavingIter).nextPos
  | 	/Users/jackson/go/src/github.com/cockroachdb/pebble/internal/keyspan/interleaving_iter.go:681
  | github.com/cockroachdb/pebble/internal/keyspan.(*InterleavingIter).yieldPosition
  | 	/Users/jackson/go/src/github.com/cockroachdb/pebble/internal/keyspan/interleaving_iter.go:807
  | github.com/cockroachdb/pebble/internal/keyspan.(*InterleavingIter).Next
  | 	/Users/jackson/go/src/github.com/cockroachdb/pebble/internal/keyspan/interleaving_iter.go:478
  | github.com/cockroachdb/pebble.(*Iterator).nextPointCurrentUserKey
  | 	/Users/jackson/go/src/github.com/cockroachdb/pebble/iterator.go:654
  | github.com/cockroachdb/pebble.(*Iterator).findNextEntry
  | 	/Users/jackson/go/src/github.com/cockroachdb/pebble/iterator.go:587
  | github.com/cockroachdb/pebble.(*Iterator).First
  | 	/Users/jackson/go/src/github.com/cockroachdb/pebble/iterator.go:1623
  | github.com/cockroachdb/pebble/metamorphic.(*retryableIter).First.func1
  | 	/Users/jackson/go/src/github.com/cockroachdb/pebble/metamorphic/retryable.go:73
  | github.com/cockroachdb/pebble/metamorphic.(*retryableIter).withRetry
  | 	/Users/jackson/go/src/github.com/cockroachdb/pebble/metamorphic/retryable.go:47
  | github.com/cockroachdb/pebble/metamorphic.(*retryableIter).First
  | 	/Users/jackson/go/src/github.com/cockroachdb/pebble/metamorphic/retryable.go:72
  | github.com/cockroachdb/pebble/metamorphic.(*iterFirstOp).run
  | 	/Users/jackson/go/src/github.com/cockroachdb/pebble/metamorphic/ops.go:1474
  | github.com/cockroachdb/pebble/metamorphic.(*Test).step
  | 	/Users/jackson/go/src/github.com/cockroachdb/pebble/metamorphic/test.go:352
  | github.com/cockroachdb/pebble/metamorphic.(*Test).Step
  | 	/Users/jackson/go/src/github.com/cockroachdb/pebble/metamorphic/test.go:341
  | github.com/cockroachdb/pebble_test.TestIteratorErrors
  | 	/Users/jackson/go/src/github.com/cockroachdb/pebble/external_test.go:85
Wraps: (2) pebble: backing file 003036 error
Wraps: (3) attached stack trace
  -- stack trace:
  | github.com/cockroachdb/pebble/vfs/errorfs.LabelledError.MaybeError
  | 	/Users/jackson/go/src/github.com/cockroachdb/pebble/vfs/errorfs/dsl.go:259
  | github.com/cockroachdb/pebble/vfs/errorfs.(*Counter).MaybeError
  | 	/Users/jackson/go/src/github.com/cockroachdb/pebble/vfs/errorfs/errorfs.go:213
  | github.com/cockroachdb/pebble/vfs/errorfs.(*Toggle).MaybeError
  | 	/Users/jackson/go/src/github.com/cockroachdb/pebble/vfs/errorfs/errorfs.go:257
  | github.com/cockroachdb/pebble/vfs/errorfs.(*errorFile).Stat
  | 	/Users/jackson/go/src/github.com/cockroachdb/pebble/vfs/errorfs/errorfs.go:505
  | github.com/cockroachdb/pebble/objstorage/objstorageprovider.newFileReadable
  | 	/Users/jackson/go/src/github.com/cockroachdb/pebble/objstorage/objstorageprovider/vfs_readable.go:37
  | github.com/cockroachdb/pebble/objstorage/objstorageprovider.(*provider).vfsOpenForReading
  | 	/Users/jackson/go/src/github.com/cockroachdb/pebble/objstorage/objstorageprovider/vfs.go:34
  | github.com/cockroachdb/pebble/objstorage/objstorageprovider.(*provider).OpenForReading
  | 	/Users/jackson/go/src/github.com/cockroachdb/pebble/objstorage/objstorageprovider/provider.go:226
  | github.com/cockroachdb/pebble.(*tableCacheValue).load
  | 	/Users/jackson/go/src/github.com/cockroachdb/pebble/table_cache.go:1123
  | github.com/cockroachdb/pebble.(*tableCacheShard).findNodeInternal.func2
  | 	/Users/jackson/go/src/github.com/cockroachdb/pebble/table_cache.go:883
  | runtime/pprof.Do
  | 	/usr/local/go/src/runtime/pprof/runtime.go:51
  | github.com/cockroachdb/pebble.(*tableCacheShard).findNodeInternal
  | 	/Users/jackson/go/src/github.com/cockroachdb/pebble/table_cache.go:882
  | github.com/cockroachdb/pebble.(*tableCacheShard).findNode
  | 	/Users/jackson/go/src/github.com/cockroachdb/pebble/table_cache.go:778
  | github.com/cockroachdb/pebble.(*tableCacheShard).newRangeKeyIter
  | 	/Users/jackson/go/src/github.com/cockroachdb/pebble/table_cache.go:596
  | github.com/cockroachdb/pebble.(*tableCacheContainer).newRangeKeyIter
  | 	/Users/jackson/go/src/github.com/cockroachdb/pebble/table_cache.go:150
  | github.com/cockroachdb/pebble/internal/keyspan.(*LevelIter).loadFile
  | 	/Users/jackson/go/src/github.com/cockroachdb/pebble/internal/keyspan/level_iter.go:183
  | github.com/cockroachdb/pebble/internal/keyspan.(*LevelIter).skipEmptyFileForward
  | 	/Users/jackson/go/src/github.com/cockroachdb/pebble/internal/keyspan/level_iter.go:415
  | github.com/cockroachdb/pebble/internal/keyspan.(*LevelIter).Next
  | 	/Users/jackson/go/src/github.com/cockroachdb/pebble/internal/keyspan/level_iter.go:345
  | github.com/cockroachdb/pebble/internal/keyspan.(*mergingIterLevel).next
  | 	/Users/jackson/go/src/github.com/cockroachdb/pebble/internal/keyspan/merging_iter.go:251
  | github.com/cockroachdb/pebble/internal/keyspan.(*MergingIter).nextEntry
  | 	/Users/jackson/go/src/github.com/cockroachdb/pebble/internal/keyspan/merging_iter.go:1041
  | github.com/cockroachdb/pebble/internal/keyspan.(*MergingIter).findNextFragmentSet
  | 	/Users/jackson/go/src/github.com/cockroachdb/pebble/internal/keyspan/merging_iter.go:865
  | github.com/cockroachdb/pebble/internal/keyspan.(*MergingIter).Next
  | 	/Users/jackson/go/src/github.com/cockroachdb/pebble/internal/keyspan/merging_iter.go:640
  | github.com/cockroachdb/pebble/internal/keyspan.(*BoundedIter).Next
  | 	/Users/jackson/go/src/github.com/cockroachdb/pebble/internal/keyspan/bounded.go:159
  | github.com/cockroachdb/pebble/internal/keyspan.(*DefragmentingIter).defragmentForward
  | 	/Users/jackson/go/src/github.com/cockroachdb/pebble/internal/keyspan/defragment.go:441
  | github.com/cockroachdb/pebble/internal/keyspan.(*DefragmentingIter).Next
  | 	/Users/jackson/go/src/github.com/cockroachdb/pebble/internal/keyspan/defragment.go:357
  | github.com/cockroachdb/pebble/internal/keyspan.(*assertIter).Next
  | 	/Users/jackson/go/src/github.com/cockroachdb/pebble/internal/keyspan/assert_iter.go:147
  | github.com/cockroachdb/pebble/internal/keyspan.(*InterleavingIter).nextPos
  | 	/Users/jackson/go/src/github.com/cockroachdb/pebble/internal/keyspan/interleaving_iter.go:681
  | github.com/cockroachdb/pebble/internal/keyspan.(*InterleavingIter).yieldPosition
  | 	/Users/jackson/go/src/github.com/cockroachdb/pebble/internal/keyspan/interleaving_iter.go:807
  | github.com/cockroachdb/pebble/internal/keyspan.(*InterleavingIter).Next
  | 	/Users/jackson/go/src/github.com/cockroachdb/pebble/internal/keyspan/interleaving_iter.go:478
  | github.com/cockroachdb/pebble.(*Iterator).nextPointCurrentUserKey
  | 	/Users/jackson/go/src/github.com/cockroachdb/pebble/iterator.go:654
  | github.com/cockroachdb/pebble.(*Iterator).findNextEntry
  | 	/Users/jackson/go/src/github.com/cockroachdb/pebble/iterator.go:587
  | github.com/cockroachdb/pebble.(*Iterator).First
  | 	/Users/jackson/go/src/github.com/cockroachdb/pebble/iterator.go:1623
  | github.com/cockroachdb/pebble/metamorphic.(*retryableIter).First.func1
  | 	/Users/jackson/go/src/github.com/cockroachdb/pebble/metamorphic/retryable.go:73
Wraps: (4) injected error
Error types: (1) *withstack.withStack (2) *errutil.withPrefix (3) *withstack.withStack (4) errorfs.LabelledError
```

**Comment by jbowens** [comment]
Another instance: https://github.com/cockroachdb/pebble/actions/runs/7589342707/job/20673776995?pr=3232

**Comment by jbowens** [comment]
A different failure, but another one surfaced by TestIteratorErrors: https://github.com/cockroachdb/pebble/actions/runs/7661341709/job/20880514829?pr=3245
