### ISSUE TITLE
db: lower bound violation in pebble tests

### ISSUE THREAD

**Issue by RaduBerinde** [cockroachdb/pebble#3364]
```
panic: lower bound f#12,21 violated by key f#14,21; wraps *keyspan.assertIter

goroutine 78074 [running]:
github.com/cockroachdb/pebble/internal/keyspan.(*assertIter).panicf(0xc00097dc20, {0x10f22786e?, 0x1?}, {0xc0008ac648?, 0x1?, 0x1?})
	/Users/runner/work/pebble/pebble/internal/keyspan/assert_iter.go:82 +0xa8
github.com/cockroachdb/pebble/internal/keyspan.(*assertIter).check(0xc00097dc20, 0xc0008074b0)
	/Users/runner/work/pebble/pebble/internal/keyspan/assert_iter.go:99 +0x1d4
github.com/cockroachdb/pebble/internal/keyspan.(*assertIter).First(0xc00097dc20)
	/Users/runner/work/pebble/pebble/internal/keyspan/assert_iter.go:134 +0x45
github.com/cockroachdb/pebble/internal/keyspan.(*filteringIter).First(0xc000807500)
	/Users/runner/work/pebble/pebble/internal/keyspan/filter.go:82 +0x23
github.com/cockroachdb/pebble/internal/keyspan.(*assertIter).First(0xc00097dcb0)
	/Users/runner/work/pebble/pebble/internal/keyspan/assert_iter.go:133 +0x23
github.com/cockroachdb/pebble/internal/keyspan.(*DefragmentingIter).First(0xc0002acb40)
	/Users/runner/work/pebble/pebble/internal/keyspan/defragment.go:289 +0x24
github.com/cockroachdb/pebble/internal/keyspan/keyspanimpl.(*MergingIter).First(0xc0003b9508)
	/Users/runner/work/pebble/pebble/internal/keyspan/keyspanimpl/merging_iter.go:615 +0x6a
github.com/cockroachdb/pebble.(*DB).loadTableRangeDelStats(0xc0008e4008, {0x10f5220b8, 0xc0009043c0}, 0xc0008f4c08, 0x6, 0xc0002856c0, 0xc0008acc08)
	/Users/runner/work/pebble/pebble/table_stats.go:375 +0xfb
github.com/cockroachdb/pebble.(*DB).loadTableStats.func1({0x10f5220b8, 0xc0009043c0})
	/Users/runner/work/pebble/pebble/table_stats.go:316 +0xf9
github.com/cockroachdb/pebble.(*tableCacheContainer).withCommonReader(0xc000072188?, 0xc0002856c0, 0xc0008acc50)
	/Users/runner/work/pebble/pebble/table_cache.go:295 +0xf3
github.com/cockroachdb/pebble.(*DB).loadTableStats(0x5?, 0x0?, 0x0?, 0x0?)
	/Users/runner/work/pebble/pebble/table_stats.go:305 +0xd4
github.com/cockroachdb/pebble.(*DB).scanReadStateTableStats(0xc0008e4008, 0xc0000b4d20, {0xc00019f490, 0x0, 0x32})
	/Users/runner/work/pebble/pebble/table_stats.go:281 +0x925
github.com/cockroachdb/pebble.(*DB).collectTableStats(0xc0008e4008)
	/Users/runner/work/pebble/pebble/table_stats.go:113 +0x236
created by github.com/cockroachdb/pebble.(*DB).maybeCollectTableStatsLocked in goroutine 78089
FAIL	github.com/cockroachdb/pebble	44.976s
```

https://github.com/cockroachdb/pebble/actions/runs/8102029032/job/22143601288?pr=3363

**Comment by RaduBerinde** [comment]
Reproduced locally, it is in `TestVirtualReadsWiring`.
