### ISSUE TITLE
internal/record: sync: unlock of unlocked mutex

### ISSUE THREAD

**Issue by petermattis** [cockroachdb/pebble#346]
Seen in a CI failure: https://travis-ci.org/cockroachdb/pebble/jobs/596159193

```
goroutine 10914 [running]:
runtime.throw(0x8836fd, 0x1e)
	/home/travis/.gimme/versions/go1.13.1.linux.amd64/src/runtime/panic.go:774 +0x72 fp=0xc004081528 sp=0xc0040814f8 pc=0x4304d2
sync.throw(0x8836fd, 0x1e)
	/home/travis/.gimme/versions/go1.13.1.linux.amd64/src/runtime/panic.go:760 +0x35 fp=0xc004081548 sp=0xc004081528 pc=0x430455
sync.(*Mutex).unlockSlow(0xc001486070, 0xffffffff)
	/home/travis/.gimme/versions/go1.13.1.linux.amd64/src/sync/mutex.go:196 +0xd6 fp=0xc004081570 sp=0xc004081548 pc=0x46bca6
sync.(*Mutex).Unlock(0xc001486070)
	/home/travis/.gimme/versions/go1.13.1.linux.amd64/src/sync/mutex.go:190 +0x48 fp=0xc004081590 sp=0xc004081570 pc=0x46bbb8
runtime.call32(0x0, 0x8973f0, 0xc004081798, 0x800000008)
	/home/travis/.gimme/versions/go1.13.1.linux.amd64/src/runtime/asm_amd64.s:539 +0x3b fp=0xc0040815c0 sp=0xc004081590 pc=0x45d5cb
panic(0x7da7a0, 0x912d60)
	/home/travis/.gimme/versions/go1.13.1.linux.amd64/src/runtime/panic.go:679 +0x1b2 fp=0xc004081650 sp=0xc0040815c0 pc=0x430012
sync.(*WaitGroup).Add(0xc003c526d0, 0xffffffffffffffff)
	/home/travis/.gimme/versions/go1.13.1.linux.amd64/src/sync/waitgroup.go:74 +0x139 fp=0xc004081688 sp=0xc004081650 pc=0x46d1f9
sync.(*WaitGroup).Done(...)
	/home/travis/.gimme/versions/go1.13.1.linux.amd64/src/sync/waitgroup.go:99
github.com/cockroachdb/pebble/internal/record.(*syncQueue).pop(0xc0014860f0, 0x2, 0x0, 0x0, 0x1c, 0x0)
	/home/travis/gopath/src/github.com/cockroachdb/pebble/internal/record/log_writer.go:128 +0x5f fp=0xc0040816e8 sp=0xc004081688 pc=0x54565f
github.com/cockroachdb/pebble/internal/record.(*LogWriter).flushLoop(0xc001486000)
	/home/travis/gopath/src/github.com/cockroachdb/pebble/internal/record/log_writer.go:312 +0x33a fp=0xc0040817d8 sp=0xc0040816e8 pc=0x545f9a
runtime.goexit()
	/home/travis/.gimme/versions/go1.13.1.linux.amd64/src/runtime/asm_amd64.s:1357 +0x1 fp=0xc0040817e0 sp=0xc0040817d8 pc=0x45f2e1
created by github.com/cockroachdb/pebble/internal/record.NewLogWriter
	/home/travis/gopath/src/github.com/cockroachdb/pebble/internal/record/log_writer.go:265 +0x2c4
```

I believe the real problem is that a panic was thrown in the `flushLoop`. 

The only stack trace which shows a test running shows `TestLogData`. I tried stressing that test locally and couldn't reproduce a failure. The failure happened on go1.13, so perhaps that is an important factor.

**Comment by petermattis** [comment]
Saw this again on CI, and now I know how to reproduce:

```
~ make stress PKG=. TESTS='TestLargeBatch|TestLogData'
GO111MODULE=off go test -v  -exec 'stress ' -run "TestLargeBatch|TestLogData" -timeout 0 .

=== RUN   TestLargeBatch


0:
  5:[a-a]
--- PASS: TestLargeBatch (0.00s)
=== RUN   TestLogData
--- FAIL: TestLogData (0.00s)
    db_test.go:529: <nil>
        goroutine 39 [running]:
        runtime/debug.Stack(0xc00022bd10, 0x13e1760, 0x151bd30)
        	/Users/pmattis/Development/go1.13/src/runtime/debug/stack.go:24 +0x9d
        github.com/cockroachdb/pebble/internal/record.(*LogWriter).flushPending.func1(0xc000067f30)
        	/Users/pmattis/Development/go/src/github.com/cockroachdb/pebble/internal/record/log_writer.go:329 +0x46
        panic(0x13e1760, 0x151bd30)
        	/Users/pmattis/Development/go1.13/src/runtime/panic.go:679 +0x1b2
        sync.(*WaitGroup).Add(0xc0001c20b0, 0xffffffffffffffff)
        	/Users/pmattis/Development/go1.13/src/sync/waitgroup.go:74 +0x139
        sync.(*WaitGroup).Done(...)
        	/Users/pmattis/Development/go1.13/src/sync/waitgroup.go:99
        github.com/cockroachdb/pebble/internal/record.(*syncQueue).pop(0xc0001f65e8, 0x1, 0x0, 0x0, 0x1c, 0x0)
        	/Users/pmattis/Development/go/src/github.com/cockroachdb/pebble/internal/record/log_writer.go:129 +0x5f
        github.com/cockroachdb/pebble/internal/record.(*LogWriter).flushPending(0xc0001f6500, 0xc00068e008, 0x1c, 0x8000, 0x0, 0x0, 0x0, 0x1, 0x0, 0x0)
        	/Users/pmattis/Development/go/src/github.com/cockroachdb/pebble/internal/record/log_writer.go:346 +0x12b
        github.com/cockroachdb/pebble/internal/record.(*LogWriter).flushLoop(0xc0001f6500)
        	/Users/pmattis/Development/go/src/github.com/cockroachdb/pebble/internal/record/log_writer.go:309 +0x1ed
        created by github.com/cockroachdb/pebble/internal/record.NewLogWriter
        	/Users/pmattis/Development/go/src/github.com/cockroachdb/pebble/internal/record/log_writer.go:265 +0x28e

FAIL
```

I also know what the problem is. Fix to arrive shortly.
