### ISSUE TITLE
TestIteratorErrors fails with SeekLT violates upper bound panic

### ISSUE THREAD

**Issue by RaduBerinde** [cockroachdb/pebble#3592]
`TestIteratorErrors` runs into
```
panic: levelIter SeekLT to key "yaxhijzhbl" violates upper bound "cgavvrurmtfg" [recovered]
```

Can reproduce at 0bc137ad1edc1608cee12dec20d4b147636b72eb with
```
go test -tags invariants -run TestIteratorErrors -v -exec stress -p 4
```

https://github.com/cockroachdb/pebble/actions/runs/8973148304/job/24642661778?pr=3590

**Comment by RaduBerinde** [comment]
At f03e7efeebfd3ffbe4e870b915e4897a0a9d02b4 the same command produces `panic: NextPrefix called while positioned on a span boundary`

**Comment by RaduBerinde** [comment]
#3593 fixes the `NextPrefix` failure above, the original 'violates upper bound' panic still happens.

**Comment by jbowens** [comment]
Looks like we violate the monotonicity during the "cascading seeks" optimization:

```
level 0: seekLT("bznjnemb")
level 1: seekLT("bznjnemb")
level 2: seekLT("bznjnemb")
level 3: seekLT("awudbpw")
level 4: seekLT("awudbpw")
level 5: seekLT("awudbpw")
level 6: seekLT("ecjlwuz@5")
2024/05/06 15:48:01 mergingIter: upper bound violation: level 6: ecjlwuz@5 > bznjnemb
goroutine 35 [running]:
runtime/debug.Stack()
	/usr/local/go/src/runtime/debug/stack.go:24 +0x64
github.com/cockroachdb/pebble.(*mergingIter).seekLT(0x14000185028, {0x14006870d08?, 0x140004d1728?, 0x1007b66c0?}, 0x140004d16d8?, 0x0)
	/Users/jackson/go/src/github.com/cockroachdb/pebble/merging_iter.go:1049 +0x134
github.com/cockroachdb/pebble.(*mergingIter).SeekLT(0x14000185028, {0x14006870d08?, 0x30?, 0x14008818180?}, 0x58?)
	/Users/jackson/go/src/github.com/cockroachdb/pebble/merging_iter.go:1103 +0x4c
github.com/cockroachdb/pebble/internal/keyspan.(*InterleavingIter).SeekLT(0x14007195330, {0x14006870d08, 0x8, 0x18}, 0x0?)
	/Users/jackson/go/src/github.com/cockroachdb/pebble/internal/keyspan/interleaving_iter.go:370 +0xd8
github.com/cockroachdb/pebble.(*Iterator).iterLastWithinBounds(0x14000184a08)
	/Users/jackson/go/src/github.com/cockroachdb/pebble/iterator.go:2099 +0x50
github.com/cockroachdb/pebble.(*Iterator).PrevWithLimit(0x14000184a08, {0x0, 0x0, 0x0})
	/Users/jackson/go/src/github.com/cockroachdb/pebble/iterator.go:2060 +0x1f8
github.com/cockroachdb/pebble.(*Iterator).Prev(...)
	/Users/jackson/go/src/github.com/cockroachdb/pebble/iterator.go:1978
github.com/cockroachdb/pebble/metamorphic.(*retryableIter).Prev.func1()
	/Users/jackson/go/src/github.com/cockroachdb/pebble/metamorphic/retryable.go:132 +0x38
github.com/cockroachdb/pebble/metamorphic.(*retryableIter).withRetry(0x1400a292870, 0x140004d18a0)
	/Users/jackson/go/src/github.com/cockroachdb/pebble/metamorphic/retryable.go:47 +0x34
github.com/cockroachdb/pebble/metamorphic.(*retryableIter).Prev(0x10?)
	/Users/jackson/go/src/github.com/cockroachdb/pebble/metamorphic/retryable.go:131 +0x44
github.com/cockroachdb/pebble/metamorphic.(*iterPrevOp).run(0x14009b1ce70, 0x0?, {0x14009a18540?, 0x14006174830?, 0x14000b66cc0?})
	/Users/jackson/go/src/github.com/cockroachdb/pebble/metamorphic/ops.go:1738 +0xa8
github.com/cockroachdb/pebble/metamorphic.(*Test).runOp(0x140004d1a38?, 0x100ed01d8?, {0x14009a18540?, 0x1011b6280?, 0x14000b66cc0?})
	/Users/jackson/go/src/github.com/cockroachdb/pebble/metamorphic/test.go:415 +0x104
github.com/cockroachdb/pebble/metamorphic.(*Test).step(0x14008c8f8c0, 0x100edef64?, 0xe?)
	/Users/jackson/go/src/github.com/cockroachdb/pebble/metamorphic/test.go:401 +0x4c
github.com/cockroachdb/pebble/metamorphic.(*Test).Step(0x14008c8f8c0)
	/Users/jackson/go/src/github.com/cockroachdb/pebble/metamorphic/test.go:390 +0x7c
github.com/cockroachdb/pebble_test.TestIteratorErrors(0x140002869c0)
	/Users/jackson/go/src/github.com/cockroachdb/pebble/external_test.go:93 +0x750
testing.tRunner(0x140002869c0, 0x101289068)
	/usr/local/go/src/testing/testing.go:1689 +0xec
created by testing.(*T).Run in goroutine 1
	/usr/local/go/src/testing/testing.go:1742 +0x318
```

**Comment by jbowens** [comment]
maybe an unsurfaced iterator error still?

**Comment by RaduBerinde** [comment]
It looks like it's been a problem for a while, I can repro failures on 2 week old commits.

**Comment by jbowens** [comment]
I'm still debugging, but it looks like a `levelIter`'s `rangeDelIterPtr` is mysteriously nil while the corresponding `mergingIterLevel`'s `rangeDelIter` is populated with a real (stale?) range deletion iterator. I'm a bit baffled.

**Comment by jbowens** [comment]
Ah, I think it's an ingested flushable so the rangeDelIter is actually an independent keyspanimpl.LevelIter. That makes more sense.

**Comment by jbowens** [comment]
Somethings up with the `keyspan.LevelIter`.

The sequence is something like:
1. We call `keyspan.SeekLE(k)` to seek the ingested flushable's range del iter to a span covering a key ≤ _k_.
2. This first performs a `FragmentIterator.SeekGE(k)`. This exhausts the iterator, indicating that there's no span covering a key ≥ k.
3. Then `keyspan.SeekLE` calls `FragmentIterator.Prev`, expecting to land on the largest span covering a key < k. This actually returns a span covering a key > k that the original `SeekGE(k)` should have surfaced.
