### ISSUE TITLE
db: inconsistent batch count panic

### ISSUE THREAD

**Issue by petermattis** [cockroachdb/pebble#540]
Seen while running the `tpcc/w=100/nodes=3/chaos=true` roachtest. From the stack, the panic is coming out of a batch application that occurred while replaying the WAL. The panic is indicating that the batch is supposed to have 7948101 entries, but applying the batch only saw 7948060 (a difference of 41 entries). Unfortunately, the underlying data for this cluster has been lost. Stressing this roachtest might reproduce.

Also, what in that roachtest is creating a batch with nearly 8m entries? That's shockingly high.

```
panic: pebble: inconsistent batch count: 7948060 vs 7948101 [recovered]
        panic: pebble: inconsistent batch count: 7948060 vs 7948101

goroutine 37 [running]:
panic(0x3d820a0, 0xc0009f7250)
        /usr/local/go/src/runtime/panic.go:722 +0x2c2 fp=0xc000b09358 sp=0xc000b092c8 pc=0x792752
github.com/cockroachdb/pebble.Open.func1(0xc000b09db8, 0xc001028f00, 0xc0001d2d00)
        /go/src/github.com/cockroachdb/pebble/open.go:76 +0x186 fp=0xc000b093b0 sp=0xc000b09358 pc=0x2bca336
runtime.call32(0x0, 0x4476758, 0xc000b09c08, 0x1800000018)
        /usr/local/go/src/runtime/asm_amd64.s:539 +0x3b fp=0xc000b093e0 sp=0xc000b093b0 pc=0x7c10ab
panic(0x3d820a0, 0xc0009f7250)
        /usr/local/go/src/runtime/panic.go:679 +0x1b2 fp=0xc000b09470 sp=0xc000b093e0 pc=0x792642
github.com/cockroachdb/pebble.(*memTable).apply(0xc00027ed20, 0xc000b09988, 0x79470f, 0x0, 0x0)
        /go/src/github.com/cockroachdb/pebble/mem_table.go:215 +0x46c fp=0xc000b097c0 sp=0xc000b09470 pc=0x2bb08fc
github.com/cockroachdb/pebble.(*DB).replayWAL(0xc0001d2d00, 0x1, 0xc000b09d40, 0x4bdb7c0, 0x74b49a0, 0xc000746c80, 0x1f, 0x440, 0x794745, 0x0, ...)
        /go/src/github.com/cockroachdb/pebble/open.go:448 +0xba3 fp=0xc000b09a70 sp=0xc000b097c0 pc=0x2bbabf3
github.com/cockroachdb/pebble.Open(0x7ffe8e6fec29, 0x14, 0xc001028f00, 0x0, 0x0, 0x0)
        /go/src/github.com/cockroachdb/pebble/open.go:231 +0xfa8 fp=0xc000b09da0 sp=0xc000b09a70 pc=0x2bb89b8
github.com/cockroachdb/cockroach/pkg/storage/engine.NewPebble(0x4b604a0, 0xc00060fd40, 0x0, 0x0, 0x0, 0x7ffe8e6fec29, 0x14, 0x0, 0x0, 0xc0001e6a80, ...)
        /go/src/github.com/cockroachdb/cockroach/pkg/storage/engine/pebble.go:405 +0x4cf fp=0xc000b09ef0 sp=0xc000b09da0 pc=0x2bf5dff
github.com/cockroachdb/cockroach/pkg/server.(*Config).CreateEngines(0xc0003d2808, 0x4b604a0, 0xc00060fd40, 0x0, 0x0, 0x0, 0x0, 0x0)
        /go/src/github.com/cockroachdb/cockroach/pkg/server/config.go:520 +0x1819 fp=0xc000b0a760 sp=0xc000b09ef0 pc=0x3060029
github.com/cockroachdb/cockroach/pkg/server.(*Server).Start(0xc0003d2800, 0x4b604a0, 0xc000a8c870, 0x0, 0x0)
        /go/src/github.com/cockroachdb/cockroach/pkg/server/server.go:1333 +0xb91 fp=0xc000b0b5b8 sp=0xc000b0a760 pc=0x3070b71
github.com/cockroachdb/cockroach/pkg/cli.runStart.func3.2(0xc000c761b0, 0xc000010138, 0xc0002b24f0, 0x4b604a0, 0xc000a8c870, 0x0, 0x8b2eb5b, 0xed5dcdfec, 0x0, 0x0, ...)
        /go/src/github.com/cockroachdb/cockroach/pkg/cli/start.go:708 +0x107 fp=0xc000b0be50 sp=0xc000b0b5b8 pc=0x31d95e7
github.com/cockroachdb/cockroach/pkg/cli.runStart.func3(0xc000010138, 0x4b604a0, 0xc000a8c870, 0x4bc9ac0, 0xc0002bd140, 0xc000c761b0, 0xc0002b24f0, 0x0, 0x8b2eb5b, 0xed5dcdfec, ...)
        /go/src/github.com/cockroachdb/cockroach/pkg/cli/start.go:824 +0x181 fp=0xc000b0bf80 sp=0xc000b0be50 pc=0x31db2e1
runtime.goexit()
        /usr/local/go/src/runtime/asm_amd64.s:1357 +0x1 fp=0xc000b0bf88 sp=0xc000b0bf80 pc=0x7c2dc1
created by github.com/cockroachdb/cockroach/pkg/cli.runStart
        /go/src/github.com/cockroachdb/cockroach/pkg/cli/start.go:664 +0x9dd
```

**Comment by petermattis** [comment]
Well, this is easy to reproduce. Running `tpcc/w=100/nodes=3/chaos=true` 10 times and I've seen 4 failures.

**Comment by petermattis** [comment]
That panic message is confusing. The numbers that are printed are not the batch count, but the expected vs actual seqnum after applying the batch. Another repro shows:

```
panic: pebble: inconsistent batch count: 5234363 vs 5234366
```

This corresponds to the following entry in a WAL which happens to be the last entry in the WAL:

```
7163714(12467) seq=5234361 count=5
    SET(0169f6b6757266746c00000000000003fa00,)
    SET(0169f6b6757266746c00000000000003fb00,)
```

So the count says `5`, but the batch seems to only contain 2 entries. Need to figure out where this discrepancy is coming from.

Another occurrence shows something similar:

```
panic: pebble: inconsistent batch count: 6401631 vs 640164
```

And the last entry in the WAL being replayed is:

```
13301746(2051) seq=6401625 count=21
    SET(c589c789f70b548800,)
    SET(c589c789f70b54880015f48500e11bdf6609,)
    SET(c589c78af705378800,)
    SET(c589c78af70537880015f48500e11bdf6609,)
    SET(c589c78bf703098800,)
    SET(c589c78bf70309880015f48500e11bdf6609,)
```

**Comment by petermattis** [comment]
It looks like what is happening is that we have a batch that is split across multiple WAL records. The first record for the batch happens to be the last record in a WAL block. The next record in the batch was not written, and instead we encounter a record that was written for the previous WAL incarnation. In this scenario, rather than returning `ErrInvalidChunk`, we're returning `io.EOF` which allows the partial batch to be read. The fix looks straightforward, though perhaps this is motivation to revisit #376.
