### ISSUE TITLE
db: sstable "already being compacted"

### ISSUE THREAD

**Issue by petermattis** [cockroachdb/pebble#541]
Running the `import/tpcc/warehouses=1000/nodes=32` on top of https://github.com/cockroachdb/pebble/pull/513 resulted in a crash on one of the nodes:

```
F200217 20:12:34.242780 113 compaction.go:1026  [n28] 000659 already being compacted
goroutine 113 [running]:
github.com/cockroachdb/cockroach/pkg/util/log.getStacks(0x7464d01, 0xed5dceab2, 0x0, 0xc018e4e1a0)
        /go/src/github.com/cockroachdb/cockroach/pkg/util/log/get_stacks.go:25 +0xb8
github.com/cockroachdb/cockroach/pkg/util/log.(*loggerT).outputLogEntry(0x7461c00, 0xc000000004, 0x69e6970, 0xd, 0x402, 0xc020915da0, 0x24)
        /go/src/github.com/cockroachdb/cockroach/pkg/util/log/clog.go:211 +0xa0c
github.com/cockroachdb/cockroach/pkg/util/log.addStructured(0x4b604a0, 0xc0007ca4b0, 0x4, 0x4, 0x430d2f7, 0x1c, 0xc0048a8990, 0x1, 0x1)
        /go/src/github.com/cockroachdb/cockroach/pkg/util/log/structured.go:66 +0x2c9
github.com/cockroachdb/cockroach/pkg/util/log.logDepth(0x4b604a0, 0xc0007ca4b0, 0x3, 0xc000000004, 0x430d2f7, 0x1c, 0xc0048a8990, 0x1, 0x1)
        /go/src/github.com/cockroachdb/cockroach/pkg/util/log/log.go:44 +0x8c
github.com/cockroachdb/cockroach/pkg/util/log.FatalfDepth(...)
        /go/src/github.com/cockroachdb/cockroach/pkg/util/log/log.go:174
github.com/cockroachdb/cockroach/pkg/storage/engine.pebbleLogger.Fatalf(...)
        /go/src/github.com/cockroachdb/cockroach/pkg/storage/engine/pebble.go:285
github.com/cockroachdb/pebble.(*DB).addInProgressCompaction(0xc0001c8d00, 0xc012dec000)
        /go/src/github.com/cockroachdb/pebble/compaction.go:745 +0x160
github.com/cockroachdb/pebble.(*DB).maybeScheduleCompaction(0xc0001c8d00)
        /go/src/github.com/cockroachdb/pebble/compaction.go:1026 +0x387
github.com/cockroachdb/pebble.(*DB).ingestApply(0xc0001c8d00, 0x1cb, 0xc01e3a21e8, 0x1, 0x1, 0x0, 0x0, 0x0)
        /go/src/github.com/cockroachdb/pebble/ingest.go:659 +0x5cd
github.com/cockroachdb/pebble.(*DB).Ingest.func2(0x26363)
        /go/src/github.com/cockroachdb/pebble/ingest.go:572 +0x130
github.com/cockroachdb/pebble.(*commitPipeline).AllocateSeqNum(0xc0001d1900, 0x1, 0xc018e4e6c8, 0xc018e4e700)
        /go/src/github.com/cockroachdb/pebble/commit.go:320 +0x20b
github.com/cockroachdb/pebble.(*DB).Ingest(0xc0001c8d00, 0xc0048a88c0, 0x1, 0x1, 0x1, 0xc0048a88b0)
        /go/src/github.com/cockroachdb/pebble/ingest.go:575 +0x43d
github.com/cockroachdb/cockroach/pkg/storage/engine.(*Pebble).IngestExternalFiles(0xc000dc61b0, 0x4b604a0, 0xc042023e30, 0xc0048a88b0, 0x1, 0x1, 0x0, 0x0)
        /go/src/github.com/cockroachdb/cockroach/pkg/storage/engine/pebble.go:770 +0x4c
github.com/cockroachdb/cockroach/pkg/storage.addSSTablePreApply(0x4b604a0, 0xc042023e30, 0xc000152a80, 0x4c0f220, 0xc000dc61b0, 0x4ba4e00, 0xc05985d180, 0x6, 0x1c, 0xc08bba6000, ...)
        /go/src/github.com/cockroachdb/cockroach/pkg/storage/replica_proposal.go:535 +0xb28
github.com/cockroachdb/cockroach/pkg/storage.(*replicaAppBatch).runPreApplyTriggersAfterStagingWriteBatch(0xc05e84b0c8, 0x4b604a0, 0xc042023e30, 0xc044244008, 0x0, 0x0)
        /go/src/github.com/cockroachdb/cockroach/pkg/storage/replica_application_state_machine.go:586 +0xbe7
github.com/cockroachdb/cockroach/pkg/storage.(*replicaAppBatch).Stage(0xc05e84b0c8, 0x4b40ca0, 0xc044244008, 0xc018e4f1a8, 0x2d322fb, 0xc05e84b298, 0xc05e84b2c8)
        /go/src/github.com/cockroachdb/cockroach/pkg/storage/replica_application_state_machine.go:477 +0x32d
github.com/cockroachdb/cockroach/pkg/storage/apply.mapCmdIter(0x4b9c340, 0xc05e84b298, 0xc018e4f318, 0x0, 0x0, 0x0, 0x0)
        /go/src/github.com/cockroachdb/cockroach/pkg/storage/apply/cmd.go:164 +0x161
github.com/cockroachdb/cockroach/pkg/storage/apply.(*Task).applyOneBatch(0xc018e4f830, 0x4b604a0, 0xc04206e9f0, 0x4b9c340, 0xc05e84b268, 0x0, 0x0)
        /go/src/github.com/cockroachdb/cockroach/pkg/storage/apply/task.go:270 +0x17c
github.com/cockroachdb/cockroach/pkg/storage/apply.(*Task).ApplyCommittedEntries(0xc018e4f830, 0x4b604a0, 0xc04206e9f0, 0x0, 0x0)
        /go/src/github.com/cockroachdb/cockroach/pkg/storage/apply/task.go:247 +0xfb
github.com/cockroachdb/cockroach/pkg/storage.(*Replica).handleRaftReadyRaftMuLocked(0xc05e84b000, 0x4b604a0, 0xc04206e9f0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        /go/src/github.com/cockroachdb/cockroach/pkg/storage/replica_raft.go:722 +0xdf9
github.com/cockroachdb/cockroach/pkg/storage.(*Replica).handleRaftReady(0xc05e84b000, 0x4b604a0, 0xc04206e9f0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        /go/src/github.com/cockroachdb/cockroach/pkg/storage/replica_raft.go:396 +0x186
github.com/cockroachdb/cockroach/pkg/storage.(*Store).processReady(0xc000898a00, 0x4b604a0, 0xc0009e3110, 0x71a)
        /go/src/github.com/cockroachdb/cockroach/pkg/storage/store_raft.go:487 +0x136
github.com/cockroachdb/cockroach/pkg/storage.(*raftScheduler).worker(0xc0003dd600, 0x4b604a0, 0xc0009e3110)
        /go/src/github.com/cockroachdb/cockroach/pkg/storage/scheduler.go:226 +0x29f
github.com/cockroachdb/cockroach/pkg/storage.(*raftScheduler).Start.func2(0x4b604a0, 0xc0009e3110)
        /go/src/github.com/cockroachdb/cockroach/pkg/storage/scheduler.go:166 +0x3e
github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker.func1(0xc000474180, 0xc000dc6000, 0xc000474170)
        /go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:197 +0x13e
created by github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker
        /go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:190 +0xa8
```

A few seconds before this crash we see that `000659` is in fact part of a compaction:

`I200217 20:12:28.898375 8827 compaction.go:1072  [n28] [JOB 419] compacting L0 [000629 000641 000644 000642 000643 000645 000663 000657 000660 000658 000683] (22 M) + L5 [000637 000640 000646 000654 000655 000664 000665 000666 000667 000668 000669 000670 000672 000674 000675 000676 000677 000678 000679 000680 000681 000682 000684 000685 000686 000687 000689 000690 000691 000692 000659 000636 000565 000566 000567 000569 000568 000570 000575 000579 000599 000673 000616 000639] (187 M)`

Notice that `000659` is part of L5, so intra-L0 compactions are not to blame. It is possible that I fouled something up in #513 with regards to concurrent compactions. It is also possible that something was already fouled up and #513's introduction of this assertion simply revealed that existing brokenness.

**Comment by petermattis** [comment]
Well something is broken with the concurrent compaction prohibition. `000659` is an L0 to L5 compaction. Shortly before the crash the logs show:

```
I200217 20:12:34.233121 9263 compaction.go:1072  [n28] [JOB 458] compacting L4 [000726] (9.2 M) + L5 [] (0 B)
I200217 20:12:34.233520 9263 compaction.go:1110  [n28] [JOB 458] compacted L4 [000726] (9.2 M) + L5 [] (0 B) -> L5 [000726] (9.2 M), in 0.0s, output rate 2.3 T/s
```

So we scheduled an L4 to L5 compaction while there was an existing L0 to L5 compaction. That shouldn't be possible. Is something broken in `conflictsWithInProgress`?
