### ISSUE TITLE
vfs: nil pointer dereference in memFile.Write

### ISSUE THREAD

**Issue by petermattis** [cockroachdb/pebble#560]
Seen on CI https://travis-ci.org/cockroachdb/pebble/jobs/656363897?utm_medium=notification&utm_source=email

I haven't been able to reproduce running `make stressmeta`. CI doesn't provides access to the OPTIONS or ops used by the metamorphic test. Probably should fix that.

```
--- FAIL: TestMeta (14.20s)
    --- FAIL: TestMeta/random-010 (0.96s)
        meta_test.go:206: exit status 2
            _meta/200228-173559.766/random-010/history
            
            panic: runtime error: invalid memory address or nil pointer dereference
            [signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0x53e44b]
            
            goroutine 4209 [running]:
            github.com/cockroachdb/pebble/vfs.(*memFile).Write(0xc0002da9c0, 0xc000648e38, 0x0, 0x7238, 0x0, 0x0, 0x0)
            	/home/travis/gopath/src/github.com/cockroachdb/pebble/vfs/mem_fs.go:639 +0x5b
            github.com/cockroachdb/pebble/internal/record.(*Writer).writePending(0xc000648000)
            	/home/travis/gopath/src/github.com/cockroachdb/pebble/internal/record/record.go:494 +0x98
            github.com/cockroachdb/pebble/internal/record.(*Writer).Close(0xc000648000, 0x8d63e0, 0xc000e41c70)
            	/home/travis/gopath/src/github.com/cockroachdb/pebble/internal/record/record.go:501 +0x33
            github.com/cockroachdb/pebble.(*versionSet).createManifest(0xc000784180, 0xc0000a61b0, 0x27, 0xfa5, 0xf9f, 0xfa6, 0x0, 0x0)
            	/home/travis/gopath/src/github.com/cockroachdb/pebble/version_set.go:515 +0x574
            github.com/cockroachdb/pebble.(*versionSet).logAndApply.func1(0xc000784180, 0xc000a4c3c0, 0xc000e87110, 0xc0000cf9c0, 0xc0000cf9a0, 0xfa5, 0xf9f, 0xfa6, 0x42f, 0x8dec00, ...)
            	/home/travis/gopath/src/github.com/cockroachdb/pebble/version_set.go:365 +0x8b7
            github.com/cockroachdb/pebble.(*versionSet).logAndApply(0xc000784180, 0x42f, 0xc000a4c3c0, 0xc00075e150, 0x8dec00, 0xc0002da240, 0xc0000cfc18, 0x0, 0x0)
            	/home/travis/gopath/src/github.com/cockroachdb/pebble/version_set.go:413 +0x1ad
            github.com/cockroachdb/pebble.(*DB).compact1(0xc000784000, 0xc00000c3c0, 0x0, 0x0, 0x0)
            	/home/travis/gopath/src/github.com/cockroachdb/pebble/compaction.go:1119 +0x8cd
            github.com/cockroachdb/pebble.(*DB).compact.func1(0x8dd4c0, 0xc00075e120)
            	/home/travis/gopath/src/github.com/cockroachdb/pebble/compaction.go:1065 +0xbe
            runtime/pprof.Do(0x8dd4c0, 0xc00075e120, 0xc0000b6120, 0x1, 0x1, 0xc000593798)
            	/home/travis/.gimme/versions/go1.13.8.linux.amd64/src/runtime/pprof/runtime.go:37 +0xf8
            github.com/cockroachdb/pebble.(*DB).compact(0xc000784000, 0xc00000c3c0, 0x0)
            	/home/travis/gopath/src/github.com/cockroachdb/pebble/compaction.go:1062 +0xa2
            created by github.com/cockroachdb/pebble.(*DB).maybeScheduleCompaction
            	/home/travis/gopath/src/github.com/cockroachdb/pebble/compaction.go:1056 +0x3c2
```

**Comment by petermattis** [comment]
The code in question is:

```
func (f *memFile) Write(p []byte) (int, error) {
	if !f.write {
		return 0, errors.New("pebble/vfs: file was not created for writing")
	}
	if f.n.isDir {  // <-- crash on this line.
		return 0, errors.New("pebble/vfs: cannot write a directory")
	}
```

We've already dereferenced `f`, so presumably the problem is that `f.n` is nil. How is that happening?

**Comment by petermattis** [comment]
I think the only way this can happen is if `memFile.Close()` has been called. We shouldn't be writing to a closed `memFile`.

**Comment by petermattis** [comment]
See https://travis-ci.org/github/cockroachdb/pebble/jobs/663541173?utm_medium=notification&utm_source=github_status for a CI failure with additional information about the operations and options.

**Comment by hueypark** [comment]
I am very suspicious of `versionSet.close`. We should have called `vs.manifest.Close ()` first.
https://github.com/cockroachdb/pebble/blob/2aca904b138a7dc4feba5f0ce1399021f09beda3/version_set.go#L261
However, I cannot reproduce the phenomenon. This can occur only when `Compaction` is followed by `Close`, but that parts are properly protected by `db.mu` and `d.mu.compact.cond`.
@petermattis  Do you have any other opinions?

**Comment by petermattis** [comment]
I wonder if this issue is a different symptom of the same root cause as https://github.com/cockroachdb/cockroach/issues/46366. In both cases, it looks like a compaction is completing after `DB.Close` has finished. I don't see how that is happening, but that is what the evidence is pointing towards.

**Comment by hueypark** [comment]
Thank you for letting me know. Let me look a little more carefully.

**Comment by petermattis** [comment]
@hueypark I took a look at the code this morning and didn't see anything suspicious. But clearly something is misbehaving.
