### ISSUE TITLE
db: cache unlink panic when close db 

### ISSUE THREAD

**Issue by glorv** [cockroachdb/pebble#678]
I'm trying to use pebble to sort and iter batch key-value paired and encounter panic when close db,  backtarce:
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x38 pc=0x12b725f]

goroutine 594 [running]:
github.com/cockroachdb/pebble/internal/cache.(*entry).unlink(0xc0140b1f00, 0x0)
        /root/go/pkg/mod/github.com/cockroachdb/pebble@v0.0.0-20200508213501-5a133cfa147f/internal/cache/entry.go:127 +0x3f
github.com/cockroachdb/pebble/internal/cache.(*shard).metaDel(0xc0049bc000, 0xc0140b1f00)
        /root/go/pkg/mod/github.com/cockroachdb/pebble@v0.0.0-20200508213501-5a133cfa147f/internal/cache/clockpro.go:388 +0x137
github.com/cockroachdb/pebble/internal/cache.(*shard).Free(0xc0049bc000)
        /root/go/pkg/mod/github.com/cockroachdb/pebble@v0.0.0-20200508213501-5a133cfa147f/internal/cache/clockpro.go:290 +0x83
github.com/cockroachdb/pebble/internal/cache.(*Cache).Unref(0xc000bcaaa0)
        /root/go/pkg/mod/github.com/cockroachdb/pebble@v0.0.0-20200508213501-5a133cfa147f/internal/cache/clockpro.go:706 +0x61
github.com/cockroachdb/pebble.(*DB).Close(0xc000a83600, 0x0, 0x0)
        /root/go/pkg/mod/github.com/cockroachdb/pebble@v0.0.0-20200508213501-5a133cfa147f/db.go:868 +0x32a
```
I added some debug info to the `cache.unlink` func. when panic, the cache entry is as follows:
```
fmt.Printf("e: %v, prev: %v, next: %v, e.blockLink.prev.blockLink.next: %v\n", e, e.blockLink.prev, e.blockLink.next, e.blockLink.prev.blockLink.next)
e: &{{{2 4} 7974813} {{{0 0} 0 0 0 0} <nil>} {0xc00150c180 0xc0140b1f00} {0xc00150c180 0xc0140b1f00} 4074 1 0 0xc0049bc000 1}, prev: &{{{0 0} 0} {{{0 0} 0 0 0 0} <nil>} {<nil> <nil>} {<nil> <nil>} 0 0 0 <nil> 0}, next: &{{{2 4} 842881} {{{0 0} 0 0 0 0} 0xc002ac1500} {0xc00150ca80 0xc001591080} {0xc00150ca80 0xc001591080} 4071 1 0 0xc0049bc000 1}, e.blockLink.prev.blockLink.next: <nil>
```

pebble version info:
```
github.com/cockroachdb/pebble v0.0.0-20200508213501-5a133cfa147f
```

**Comment by jbowens** [comment]
@glorv What SHA were you using? Is it more recent than 91672215c3047e5c42c24cc53ce8f3fc865d29ad?

**Comment by glorv** [comment]
> @glorv What SHA were you using? Is it more recent than [9167221](https://github.com/cockroachdb/pebble/commit/91672215c3047e5c42c24cc53ce8f3fc865d29ad)?

@jbowens  Sorry for missing the commit info. We are using https://github.com/cockroachdb/pebble/commit/5a133cfa147f571b6fcf30246902e74c2e8af62c and seems it's a different issue.

**Comment by petermattis** [comment]
@glorv Is this crash repeatable? If you provide a test which reproduces the crash we'll be able to get to the bottom of what is going on much more quickly.

You might try building with `-tags invariants` which enables various invariants checking in the cache (and in other parts of Pebble). This is quite a bit slower than non-invariants builds, but it might also pinpoint the problem. If you have a reproducible test, this is the first thing I'd try.

**Comment by glorv** [comment]
After add `-tags invariants` the panic don't appear anymore. But when I remove this, the same problem appeared right after I started the program.  And here I met another panic, maybe the root cause is the same one. 
```
panic: runtime error: slice bounds out of range [-4:]

goroutine 556 [running]:
github.com/cockroachdb/pebble/sstable.(*blockIter).init(0xc002918070, 0x1bfbe40, 0x1, 0x0, 0x0, 0x0, 0xc001786990, 0x12e795d)
        /root/go/pkg/mod/github.com/cockroachdb/pebble@v0.0.0-20200508213501-5a133cfa147f/sstable/block.go:257 +0x1be
github.com/cockroachdb/pebble/sstable.(*blockIter).initHandle(0xc002918070, 0x1bfbe40, 0x0, 0xc004830000, 0x0, 0x0, 0x0)
        /root/go/pkg/mod/github.com/cockroachdb/pebble@v0.0.0-20200508213501-5a133cfa147f/sstable/block.go:276 +0xa8
github.com/cockroachdb/pebble/sstable.(*singleLevelIterator).init(0xc002918000, 0xc000159600, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0xc0092f5801)
        /root/go/pkg/mod/github.com/cockroachdb/pebble@v0.0.0-20200508213501-5a133cfa147f/sstable/reader.go:143 +0x116
github.com/cockroachdb/pebble/sstable.(*Reader).NewIter(0xc000159600, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x2801, 0x1, 0xa, ...)
        /root/go/pkg/mod/github.com/cockroachdb/pebble@v0.0.0-20200508213501-5a133cfa147f/sstable/reader.go:1134 +0x1ac
github.com/cockroachdb/pebble.(*tableCacheShard).newIters(0xc000b36420, 0xc00288c280, 0xc000164138, 0x0, 0x4fc03d, 0xc000965200, 0x25, 0x26, 0xc004276d20, 0x25)
        /root/go/pkg/mod/github.com/cockroachdb/pebble@v0.0.0-20200508213501-5a133cfa147f/table_cache.go:184 +0x107
github.com/cockroachdb/pebble.(*tableCache).newIters(0xc000b30098, 0xc00288c280, 0xc000164138, 0x0, 0x26, 0xc004276d20, 0x25, 0x5a, 0x1, 0xc000164150)
        /root/go/pkg/mod/github.com/cockroachdb/pebble@v0.0.0-20200508213501-5a133cfa147f/table_cache.go:58 +0x78
github.com/cockroachdb/pebble.(*levelIter).loadFile(0xc0001640f0, 0x0, 0x1, 0x30)
        /root/go/pkg/mod/github.com/cockroachdb/pebble@v0.0.0-20200508213501-5a133cfa147f/level_iter.go:304 +0x151
github.com/cockroachdb/pebble.(*levelIter).SeekGE(0xc0001640f0, 0xc000965140, 0x25, 0x30, 0x0, 0xc001786ce8, 0x41786e, 0x7fe8c7a22780)
        /root/go/pkg/mod/github.com/cockroachdb/pebble@v0.0.0-20200508213501-5a133cfa147f/level_iter.go:351 +0x91
github.com/cockroachdb/pebble.(*mergingIter).seekGE(0xc000163950, 0xc000965140, 0x25, 0x30, 0x0)
        /root/go/pkg/mod/github.com/cockroachdb/pebble@v0.0.0-20200508213501-5a133cfa147f/merging_iter.go:745 +0x56b
github.com/cockroachdb/pebble.(*mergingIter).SeekGE(0xc000163950, 0xc000965140, 0x25, 0x30, 0xc000163800, 0x42e36a, 0x0, 0x0)
        /root/go/pkg/mod/github.com/cockroachdb/pebble@v0.0.0-20200508213501-5a133cfa147f/merging_iter.go:800 +0x8b
github.com/cockroachdb/pebble.(*Iterator).First(0xc000163800, 0x0)
        /root/go/pkg/mod/github.com/cockroachdb/pebble@v0.0.0-20200508213501-5a133cfa147f/iterator.go:389 +0xa0
```

**Comment by petermattis** [comment]
@glorv We have never seen this second panic before. Since it also relates to cache data, I'd suspect the same root cause. Since we have never seen it before, I suspect it relates to something you're doing. If you have a reproducible test case, please share it.

**Comment by petermattis** [comment]
@glorv Have you been able to reproduce this crash or determine its cause?

**Comment by glorv** [comment]
> @glorv Have you been able to reproduce this crash or determine its cause?
I found my program occasional set `CGO_ENABLED=0`, then the panic is easily recurred. Buf after change to `CGO_ENABLED=1` it never appear again. And when I update to the latest version,   build with `COGO_ENABLED=0` which directly cause a panic. So seems this should not be an issues any more and can be closed.
