### ISSUE TITLE
panic while running benchmarks

### ISSUE THREAD

**Issue by raulk** [cockroachdb/pebble#902]
```
⟩ go version
go version go1.14 darwin/amd64
⟩ git rev-parse HEAD
284ba06683916885c62c6839c87032d9ad1f3fad
⟩ go test -v -count=1 -run=NONE -bench  ./...
goos: darwin
goarch: amd64
pkg: github.com/cockroachdb/pebble
BenchmarkBatchSet
BenchmarkIndexedBatchSet
BenchmarkBatchSetDeferred
BenchmarkIndexedBatchSetDeferred
BenchmarkCommitPipeline
BenchmarkCommitPipeline/parallel=1
BenchmarkCommitPipeline/parallel=1-16  	 1000000	      1016 ns/op	  15.75 MB/s
BenchmarkCommitPipeline/parallel=2
BenchmarkCommitPipeline/parallel=2-16  	 1000000	      1039 ns/op	  15.40 MB/s
BenchmarkCommitPipeline/parallel=4
BenchmarkCommitPipeline/parallel=4-16  	 1000000	      1009 ns/op	  15.85 MB/s
BenchmarkCommitPipeline/parallel=8
BenchmarkCommitPipeline/parallel=8-16  	 1000000	      1111 ns/op	  14.41 MB/s
BenchmarkCommitPipeline/parallel=16
BenchmarkCommitPipeline/parallel=16-16 	 1206015	       976 ns/op	  16.39 MB/s
BenchmarkCommitPipeline/parallel=32
BenchmarkCommitPipeline/parallel=32-16 	 1000000	      1086 ns/op	  14.74 MB/s
BenchmarkCommitPipeline/parallel=64
BenchmarkCommitPipeline/parallel=64-16 	 1000000	      1260 ns/op	  12.70 MB/s
BenchmarkCommitPipeline/parallel=128
BenchmarkCommitPipeline/parallel=128-16         	 1000000	      1264 ns/op	  12.65 MB/s
BenchmarkDelete
BenchmarkDelete/delete
BenchmarkDelete/delete-16                       	      30	  39930403 ns/op
BenchmarkDelete/single-delete
BenchmarkDelete/single-delete-16                	      31	  40606620 ns/op
BenchmarkIteratorSeekGE
BenchmarkIteratorNext
BenchmarkIteratorPrev
BenchmarkLevelIterSeekGE
BenchmarkLevelIterSeekGE/restart=16
BenchmarkLevelIterSeekGE/restart=16/count=5
panic: runtime error: invalid memory address or nil pointer dereference
	panic: runtime error: invalid memory address or nil pointer dereference
	panic: runtime error: invalid memory address or nil pointer dereference
	panic: runtime error: invalid memory address or nil pointer dereference
	panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x14 pc=0x447609e]

goroutine 19673 [running]:
github.com/cockroachdb/pebble/vfs.(*memFile).Close(0xc00096c0c0, 0x48a85a0, 0xc00096c0c0)
	/Users/raul/W/pl/pebble/vfs/mem_fs.go:608 +0x2e
panic(0x46959e0, 0x4cf7c00)
	/usr/local/Cellar/go/1.14/libexec/src/runtime/panic.go:973 +0x396
github.com/cockroachdb/pebble/vfs.(*memFile).Close(0xc00096c0f0, 0x48a85a0, 0xc00096c0f0)
	/Users/raul/W/pl/pebble/vfs/mem_fs.go:608 +0x2e
panic(0x46959e0, 0x4cf7c00)
	/usr/local/Cellar/go/1.14/libexec/src/runtime/panic.go:973 +0x396
github.com/cockroachdb/pebble/vfs.(*memFile).Close(0xc00096c150, 0x48a85a0, 0xc00096c150)
	/Users/raul/W/pl/pebble/vfs/mem_fs.go:608 +0x2e
panic(0x46959e0, 0x4cf7c00)
	/usr/local/Cellar/go/1.14/libexec/src/runtime/panic.go:973 +0x396
github.com/cockroachdb/pebble/vfs.(*memFile).Close(0xc00096c180, 0x48a85a0, 0xc00096c180)
	/Users/raul/W/pl/pebble/vfs/mem_fs.go:608 +0x2e
panic(0x46959e0, 0x4cf7c00)
	/usr/local/Cellar/go/1.14/libexec/src/runtime/panic.go:973 +0x396
github.com/cockroachdb/pebble/vfs.(*memFile).Close(0xc00096c1b0, 0x48a85a0, 0xc00096c1b0)
	/Users/raul/W/pl/pebble/vfs/mem_fs.go:608 +0x2e
github.com/cockroachdb/pebble.buildLevelIterTables(0xc0002e2700, 0x8000, 0x10, 0x5, 0xc00009f080, 0x5, 0x5, 0xc00096c420, 0x5, 0x5, ...)
	/Users/raul/W/pl/pebble/level_iter_test.go:415 +0xd8b
github.com/cockroachdb/pebble.BenchmarkLevelIterSeekGE.func1.1(0xc0002e2700)
	/Users/raul/W/pl/pebble/level_iter_test.go:427 +0x64
testing.(*B).runN(0xc0002e2700, 0x1)
	/usr/local/Cellar/go/1.14/libexec/src/testing/benchmark.go:191 +0xe8
testing.(*B).run1.func1(0xc0002e2700)
	/usr/local/Cellar/go/1.14/libexec/src/testing/benchmark.go:231 +0x57
created by testing.(*B).run1
	/usr/local/Cellar/go/1.14/libexec/src/testing/benchmark.go:224 +0x7d
exit status 2
FAIL	github.com/cockroachdb/pebble	16.912s
```

**Comment by raulk** [comment]
Looks like go benchmarks are not run at all on CI...

**Comment by jbowens** [comment]
Thanks for reporting the failing benchmarks: it looks like a few weren't updated to clean up after themselves appropriately, resulting in panics in the test code.

The Go microbenchmarks are not useful for evaluating the performance of Pebble overall. We run only relevant microbenchmarks when changing particular components/packages. The program in cmd/pebble is useful for Pebble performance testing. This program is used to populate our [nightly Pebble benchmarks](https://cockroachdb.github.io/pebble/) (linked from the README).

**Comment by raulk** [comment]
@jbowens I know, but I was trying to wrap my head around a write performance discrepancy, and I thought I'd compare with some microbenchmarks. It turns out that pebble fsync's by default (whereas I thought it would _not_ fsync by default). Just using `pebble.NoSync` when performing the operations made things a lot more reasonable.
