### ISSUE TITLE
panic: runtime error: slice bounds out of range [12:0]

### ISSUE THREAD

**Issue by karalabe** [cockroachdb/pebble#909]
Got a funky crash for y'all :) 

```
panic: runtime error: slice bounds out of range [12:0]

goroutine 1894031 [running]:
github.com/cockroachdb/pebble.(*Batch).Reader(...)
	github.com/cockroachdb/pebble@v0.0.0-20200915204653-08b545a1f540/batch.go:843
github.com/ethereum/go-ethereum/ethdb/pebble.(*batch).Replay(0xc04f8b3d40, 0x183e220, 0xc04d028030, 0x370c45b3b647966f, 0x94dc3868ae639cf7)
	github.com/ethereum/go-ethereum/ethdb/pebble/pebble.go:322 +0x2dc
[...]
```

**Comment by jbowens** [comment]
Thanks for the report! Fix in #910.
