### ISSUE TITLE
Some troubles on linux 

### ISSUE THREAD

**Issue by moredure** [cockroachdb/pebble#954]
compiled on macos 10.13.6 GOOS=linux go build
linux server (bare metal) fs backed by software RAID
any ideas how to fix it?
```go
type PebbleQueue struct {
	sync.Mutex

	key []byte

	db *pebble.DB

	head, tail uint64
}

func (pq *PebbleQueue) Enqueue(value []byte) error {
	pq.Lock()
	defer pq.Unlock()

	pq.tail++
	binary.BigEndian.PutUint64(pq.key[8:16], pq.tail)
	return pq.db.Set(pq.key, value, pebble.NoSync)
}

func (pq *PebbleQueue) Dequeue() ([]byte, error) {
	pq.Lock()
	defer pq.Unlock()

	pq.head++
	binary.BigEndian.PutUint64(pq.key[8:16], pq.head)

	v, closer, err := pq.db.Get(pq.key)
	if err != nil {
		return nil, err
	}
	value := make([]byte, len(v))
	copy(value, v)
	if err := closer.Close(); err != nil {
		return nil, err
	}
	return value, pq.db.Delete(pq.key, pebble.NoSync)
}

func (pq *PebbleQueue) EnqueueString(value string) error {
	return pq.Enqueue([]byte(value))
}

func (pq *PebbleQueue) DequeueString() (string, error) {
	v, err := pq.Dequeue()
	if err != nil {
		return "", err
	}
	return string(v), nil
}

func (pq *PebbleQueue) Len() uint64 {
	pq.Lock()
	defer pq.Unlock()
	return pq.tail - pq.head
}

func (pq *PebbleQueue) IsEmpty() bool {
	return pq.Len() == 0
}

func NewPebbleQueue(db *pebble.DB, id uint64) (*PebbleQueue, error) {
	dq := &PebbleQueue{
		db:  db,
		key: make([]byte, 16),
	}
	binary.BigEndian.PutUint64(dq.key[0:8], id)
	return dq, nil
}


func main() {
	db, err := pebble.Open("/tmp/testdb1", nil)
	if err != nil {
		panic(err)
	}
	defer db.Close()

	d, err := NewPebbleQueue(db, 1)
	if err != nil {
		panic(err)
	}
	s := time.Now()
	for i := 0; i < 1000000; i ++ {
		d.EnqueueString(strconv.Itoa(i))
	}
	fmt.Println(time.Since(s))
	s = time.Now()
	for i := 0; i < 1000000; i ++ {
		d.Dequeue()
	}
	fmt.Println(time.Since(s))
```

```
2.476130086s
unexpected fault address 0x100000018
fatal error: fault
[signal SIGSEGV: segmentation violation code=0x1 addr=0x100000018 pc=0x88a08b]

goroutine 1 [running]:
runtime.throw(0xa2227a, 0x5)
	/usr/local/Cellar/go/1.15.2/libexec/src/runtime/panic.go:1116 +0x72 fp=0xc0012696a8 sp=0xc001269678 pc=0x435a92
runtime.sigpanic()
	/usr/local/Cellar/go/1.15.2/libexec/src/runtime/signal_unix.go:727 +0x405 fp=0xc0012696d8 sp=0xc0012696a8 pc=0x44b305
github.com/cockroachdb/pebble/internal/cache.(*refcnt).release(...)
	/Users/myuser/go/pkg/mod/github.com/cockroachdb/pebble@v0.0.0-20200930153740-4e0eb739ab1a/internal/cache/refcnt_normal.go:30
github.com/cockroachdb/pebble/internal/cache.(*Value).release(...)
	/Users/myuser/go/pkg/mod/github.com/cockroachdb/pebble@v0.0.0-20200930153740-4e0eb739ab1a/internal/cache/value.go:43
github.com/cockroachdb/pebble/internal/cache.(*entry).setValue(...)
	/Users/myuser/go/pkg/mod/github.com/cockroachdb/pebble@v0.0.0-20200930153740-4e0eb739ab1a/internal/cache/entry.go:141
github.com/cockroachdb/pebble/internal/cache.(*shard).metaDel(0xc000001680, 0xc000062300)
	/Users/myuser/go/pkg/mod/github.com/cockroachdb/pebble@v0.0.0-20200930153740-4e0eb739ab1a/internal/cache/clockpro.go:322 +0x4b fp=0xc001269710 sp=0xc0012696d8 pc=0x88a08b
github.com/cockroachdb/pebble/internal/cache.(*shard).runHandTest(0xc000001680)
	/Users/myuser/go/pkg/mod/github.com/cockroachdb/pebble@v0.0.0-20200930153740-4e0eb739ab1a/internal/cache/clockpro.go:469 +0xa5 fp=0xc001269738 sp=0xc001269710 pc=0x88a8a5
github.com/cockroachdb/pebble/internal/cache.(*shard).runHandHot(0xc000001680)
	/Users/myuser/go/pkg/mod/github.com/cockroachdb/pebble@v0.0.0-20200930153740-4e0eb739ab1a/internal/cache/clockpro.go:434 +0xc8 fp=0xc001269750 sp=0xc001269738 pc=0x88a7c8
github.com/cockroachdb/pebble/internal/cache.(*shard).runHandCold(0xc000001680)
	/Users/myuser/go/pkg/mod/github.com/cockroachdb/pebble@v0.0.0-20200930153740-4e0eb739ab1a/internal/cache/clockpro.go:428 +0x90 fp=0xc001269770 sp=0xc001269750 pc=0x88a5b0
github.com/cockroachdb/pebble/internal/cache.(*shard).runHandTest(0xc000001680)
	/Users/myuser/go/pkg/mod/github.com/cockroachdb/pebble@v0.0.0-20200930153740-4e0eb739ab1a/internal/cache/clockpro.go:456 +0xfe fp=0xc001269798 sp=0xc001269770 pc=0x88a8fe
github.com/cockroachdb/pebble/internal/cache.(*shard).runHandHot(0xc000001680)
	/Users/myuser/go/pkg/mod/github.com/cockroachdb/pebble@v0.0.0-20200930153740-4e0eb739ab1a/internal/cache/clockpro.go:434 +0xc8 fp=0xc0012697b0 sp=0xc001269798 pc=0x88a7c8
github.com/cockroachdb/pebble/internal/cache.(*shard).runHandCold(0xc000001680)
	/Users/myuser/go/pkg/mod/github.com/cockroachdb/pebble@v0.0.0-20200930153740-4e0eb739ab1a/internal/cache/clockpro.go:428 +0x90 fp=0xc0012697d0 sp=0xc0012697b0 pc=0x88a5b0
github.com/cockroachdb/pebble/internal/cache.(*shard).runHandTest(0xc000001680)
	/Users/myuser/go/pkg/mod/github.com/cockroachdb/pebble@v0.0.0-20200930153740-4e0eb739ab1a/internal/cache/clockpro.go:456 +0xfe fp=0xc0012697f8 sp=0xc0012697d0 pc=0x88a8fe
github.com/cockroachdb/pebble/internal/cache.(*shard).runHandHot(0xc000001680)
	/Users/myuser/go/pkg/mod/github.com/cockroachdb/pebble@v0.0.0-20200930153740-4e0eb739ab1a/internal/cache/clockpro.go:434 +0xc8 fp=0xc001269810 sp=0xc0012697f8 pc=0x88a7c8
github.com/cockroachdb/pebble/internal/cache.(*shard).runHandCold(0xc000001680)
	/Users/myuser/go/pkg/mod/github.com/cockroachdb/pebble@v0.0.0-20200930153740-4e0eb739ab1a/internal/cache/clockpro.go:428 +0x90 fp=0xc001269830 sp=0xc001269810 pc=0x88a5b0
github.com/cockroachdb/pebble/internal/cache.(*shard).runHandTest(0xc000001680)
	/Users/myuser/go/pkg/mod/github.com/cockroachdb/pebble@v0.0.0-20200930153740-4e0eb739ab1a/internal/cache/clockpro.go:456 +0xfe fp=0xc001269858 sp=0xc001269830 pc=0x88a8fe
github.com/cockroachdb/pebble/internal/cache.(*shard).runHandHot(0xc000001680)
	/Users/myuser/go/pkg/mod/github.com/cockroachdb/pebble@v0.0.0-20200930153740-4e0eb739ab1a/internal/cache/clockpro.go:434 +0xc8 fp=0xc001269870 sp=0xc001269858 pc=0x88a7c8
github.com/cockroachdb/pebble/internal/cache.(*shard).runHandCold(0xc000001680)
	/Users/myuser/go/pkg/mod/github.com/cockroachdb/pebble@v0.0.0-20200930153740-4e0eb739ab1a/internal/cache/clockpro.go:428 +0x90 fp=0xc001269890 sp=0xc001269870 pc=0x88a5b0
github.com/cockroachdb/pebble/internal/cache.(*shard).evict(0xc000001680)
	/Users/myuser/go/pkg/mod/github.com/cockroachdb/pebble@v0.0.0-20200930153740-4e0eb739ab1a/internal/cache/clockpro.go:402 +0x2d fp=0xc0012698a8 sp=0xc001269890 pc=0x88a4cd
github.com/cockroachdb/pebble/internal/cache.(*shard).Reserve(0xc000001680, 0x200000)
	/Users/myuser/go/pkg/mod/github.com/cockroachdb/pebble@v0.0.0-20200930153740-4e0eb739ab1a/internal/cache/clockpro.go:254 +0x4d fp=0xc0012698c8 sp=0xc0012698a8 pc=0x889c8d
github.com/cockroachdb/pebble/internal/cache.(*Cache).Reserve(0xc000058410, 0x400000, 0xc000000300)
	/Users/myuser/go/pkg/mod/github.com/cockroachdb/pebble@v0.0.0-20200930153740-4e0eb739ab1a/internal/cache/clockpro.go:717 +0x98 fp=0xc001269900 sp=0xc0012698c8 pc=0x88b5b8
github.com/cockroachdb/pebble.(*DB).newMemTable(0xc00003b000, 0x23, 0xf8e0f, 0xc000140000, 0xc00004e660)
	/Users/myuser/go/pkg/mod/github.com/cockroachdb/pebble@v0.0.0-20200930153740-4e0eb739ab1a/db.go:1214 +0xa5 fp=0xc0012699a0 sp=0xc001269900 pc=0x8dbbc5
github.com/cockroachdb/pebble.(*DB).makeRoomForWrite(0xc00003b000, 0xc0000be1e0, 0x1e, 0x400)
	/Users/myuser/go/pkg/mod/github.com/cockroachdb/pebble@v0.0.0-20200930153740-4e0eb739ab1a/db.go:1459 +0x3c6 fp=0xc001269b78 sp=0xc0012699a0 pc=0x8dc1c6
github.com/cockroachdb/pebble.(*DB).commitWrite(0xc00003b000, 0xc0000be1e0, 0x0, 0x0, 0xc0000a6678, 0xc0000be1e0, 0xc0000a6678)
	/Users/myuser/go/pkg/mod/github.com/cockroachdb/pebble@v0.0.0-20200930153740-4e0eb739ab1a/db.go:628 +0xc5 fp=0xc001269c10 sp=0xc001269b78 pc=0x8d7ac5
github.com/cockroachdb/pebble.(*DB).commitWrite-fm(0xc0000be1e0, 0x0, 0x0, 0xc0003fd350, 0xc0003fd350, 0xc001269d48)
	/Users/myuser/go/pkg/mod/github.com/cockroachdb/pebble@v0.0.0-20200930153740-4e0eb739ab1a/db.go:601 +0x48 fp=0xc001269c58 sp=0xc001269c10 pc=0x923d48
github.com/cockroachdb/pebble.(*commitPipeline).prepare(0xc0000a6600, 0xc0000be1e0, 0x0, 0x10, 0xe807c01, 0x473c65)
	/Users/myuser/go/pkg/mod/github.com/cockroachdb/pebble@v0.0.0-20200930153740-4e0eb739ab1a/commit.go:377 +0x175 fp=0xc001269cd8 sp=0xc001269c58 pc=0x8bdf55
github.com/cockroachdb/pebble.(*commitPipeline).Commit(0xc0000a6600, 0xc0000be1e0, 0x473800, 0x473c65, 0x0)
	/Users/myuser/go/pkg/mod/github.com/cockroachdb/pebble@v0.0.0-20200930153740-4e0eb739ab1a/commit.go:253 +0x73 fp=0xc001269d18 sp=0xc001269cd8 pc=0x8bd953
github.com/cockroachdb/pebble.(*DB).Apply(0xc00003b000, 0xc0000be1e0, 0xe05de7, 0x10, 0xe05de7)
	/Users/myuser/go/pkg/mod/github.com/cockroachdb/pebble@v0.0.0-20200930153740-4e0eb739ab1a/db.go:556 +0x110 fp=0xc001269da8 sp=0xc001269d18 pc=0x8d74f0
github.com/cockroachdb/pebble.(*DB).Delete(0xc00003b000, 0xc000020700, 0x10, 0x10, 0xe05de7, 0x0, 0xc00088d89c)
	/Users/myuser/go/pkg/mod/github.com/cockroachdb/pebble@v0.0.0-20200930153740-4e0eb739ab1a/db.go:454 +0xbb fp=0xc001269df8 sp=0xc001269da8 pc=0x8d6ddb
main.(*PebbleQueue).Dequeue(0xc000058690, 0x0, 0x0, 0x0, 0x0, 0x0)
	/Users/myuser/Desktop/myapp/main.go:49 +0x225 fp=0xc001269eb0 sp=0xc001269df8 pc=0x9257c5
main.main()
	/Users/myuser/Desktop/myapp/main.go:191 +0x25f fp=0xc001269f88 sp=0xc001269eb0 pc=0x925e9f
runtime.main()
	/usr/local/Cellar/go/1.15.2/libexec/src/runtime/proc.go:204 +0x209 fp=0xc001269fe0 sp=0xc001269f88 pc=0x438289
runtime.goexit()
	/usr/local/Cellar/go/1.15.2/libexec/src/runtime/asm_amd64.s:1374 +0x1 fp=0xc001269fe8 sp=0xc001269fe0 pc=0x46a121

goroutine 6 [chan receive]:
github.com/cockroachdb/pebble.(*tableCacheShard).releaseLoop.func1(0xacafe0, 0xc000065ef0)
	/Users/myuser/go/pkg/mod/github.com/cockroachdb/pebble@v0.0.0-20200930153740-4e0eb739ab1a/table_cache.go:171 +0x76
runtime/pprof.Do(0xacafe0, 0xc000065ef0, 0xc00000cce0, 0x1, 0x1, 0xc0000387b8)
	/usr/local/Cellar/go/1.15.2/libexec/src/runtime/pprof/runtime.go:40 +0xcc
github.com/cockroachdb/pebble.(*tableCacheShard).releaseLoop(0xc0000bc200)
	/Users/myuser/go/pkg/mod/github.com/cockroachdb/pebble@v0.0.0-20200930153740-4e0eb739ab1a/table_cache.go:170 +0x89
created by github.com/cockroachdb/pebble.(*tableCacheShard).init
	/Users/myuser/go/pkg/mod/github.com/cockroachdb/pebble@v0.0.0-20200930153740-4e0eb739ab1a/table_cache.go:162 +0x1a5

goroutine 7 [select]:
github.com/cockroachdb/pebble/vfs.(*diskHealthCheckingFile).startTicker.func1(0xc00007e5c0)
	/Users/myuser/go/pkg/mod/github.com/cockroachdb/pebble@v0.0.0-20200930153740-4e0eb739ab1a/vfs/disk_health.go:63 +0x105
created by github.com/cockroachdb/pebble/vfs.(*diskHealthCheckingFile).startTicker
	/Users/myuser/go/pkg/mod/github.com/cockroachdb/pebble@v0.0.0-20200930153740-4e0eb739ab1a/vfs/disk_health.go:58 +0x50

goroutine 88 [runnable]:
github.com/cockroachdb/pebble/internal/record.NewLogWriter.func2(0xc000140000)
	/Users/myuser/go/pkg/mod/github.com/cockroachdb/pebble@v0.0.0-20200930153740-4e0eb739ab1a/internal/record/log_writer.go:313
created by github.com/cockroachdb/pebble/internal/record.NewLogWriter
	/Users/myuser/go/pkg/mod/github.com/cockroachdb/pebble@v0.0.0-20200930153740-4e0eb739ab1a/internal/record/log_writer.go:313 +0x2ea

goroutine 87 [runnable]:
github.com/cockroachdb/pebble/vfs.(*diskHealthCheckingFile).startTicker.func1(0xc00007e100)
	/Users/myuser/go/pkg/mod/github.com/cockroachdb/pebble@v0.0.0-20200930153740-4e0eb739ab1a/vfs/disk_health.go:58
created by github.com/cockroachdb/pebble/vfs.(*diskHealthCheckingFile).startTicker
	/Users/myuser/go/pkg/mod/github.com/cockroachdb/pebble@v0.0.0-20200930153740-4e0eb739ab1a/vfs/disk_health.go:58 +0x50

goroutine 82 [runnable]:
github.com/cockroachdb/pebble/vfs.(*diskHealthCheckingFile).startTicker.func1(0xc00007e780)
	/Users/myuser/go/pkg/mod/github.com/cockroachdb/pebble@v0.0.0-20200930153740-4e0eb739ab1a/vfs/disk_health.go:63 +0x105
created by github.com/cockroachdb/pebble/vfs.(*diskHealthCheckingFile).startTicker
	/Users/myuser/go/pkg/mod/github.com/cockroachdb/pebble@v0.0.0-20200930153740-4e0eb739ab1a/vfs/disk_health.go:58 +0x50
```

**Comment by moredure** [comment]
With logging pebble/table: corrupt top level index entry this error happens first, than dequeue panics

**Comment by moredure** [comment]
On macos everything works just fine

**Comment by petermattis** [comment]
@moredure Is this reproducible? That is, can you start from a non-existent DB and reproduce the first time the program is run?

What version of Linux are you running on? What version of Go are you using?

**Comment by moredure** [comment]
Hello @petermattis , also DisableWal helps on first run, then program fails

**Comment by moredure** [comment]
Fails even with 
```go
	db, err := pebble.Open("/tmp/testdb1", &pebble.Options{
		FS: vfs.NewMem(),
	})
```

**Comment by moredure** [comment]
test on other linux server with 5.4.0 kernel, fails as well

**Comment by moredure** [comment]
With compiled on linux everything seems fine.
